### ISSUE TITLE
bitbucket.org configuration

### ISSUE THREAD

**Issue by ferdinandyb** [ralphbean/bugwarrior#1002]
I managed to configure bugwarrior with a gitlab instance, but I haven't been able to figure out a) how to configure bitbucket.org. I have a setup exactly like that in the docs (username, key, secret), but it complains I don't have a "login" configured, but if I set up a login (with my username), then it says it's unable to retrieve a password from the keyring. Since I have a key and a secret I really shouldn't need to supply my password, right?

**Comment by ryneeverett** [comment]
I suspect you're looking at the `latest` docs while using a stable release of bugwarrior. You can select the `stable` docs in the bottom left hand corner pop-up box on readthedocs.

I've been burned by this myself a number of times as it's quite subtle. I wonder if there's a theme or css customization we could make to make the stable/latest distinction louder.

**Comment by ferdinandyb** [comment]
Oh, my bad, I was really looking at the `latest` docs. Using password I got  a 401 refresh token error. I have 2fa on the account, so probably password is not going to work anyway. If the new release is not very far, I think I will just wait for that. Thanks for the help!

As a note about the docs: another option would be making `stable` the default when you open, although probably a theme difference, or having the version in a more prominent place is also useful. Not that I shouldn't have thought about checking if I'm reading the right docs :)

**Comment by ryneeverett** [comment]
> Using password I got a 401 refresh token error. I have 2fa on the account, so probably password is not going to work anyway.

I actually don't think it's possible to use bitbucket with the stable release at the moment. See #888. TLDR, password authentication is disabled and the oauth workflow has been updated.

> If the new release is not very far, I think I will just wait for that.

I wish I could give a clearer answer to this but I haven't been able to contact any maintainers with the ability to cut a release for the past year or so. (See #812.) However, if the bitbucket service is utterly broken on the latest release, as I suspect it is, that's probably a good reason to push harder.

**Comment by ferdinandyb** [comment]
Thanks! In that case, I'll wait it out. I'm just trying out the workflow with taskwarrior+bugwarrior and gitlab and github is going to be enough for that (although I gotta say that I already love it, combined with the vimwiki integration). 

Anyway, I think this can be closed. And good luck with reaching the necessary people!
