### ISSUE TITLE
Issue with azuredevops service

### ISSUE THREAD

**Issue by fslef** [ralphbean/bugwarrior#1006]
I have setup the following service in the `bugwarriorrc`

``` ini
[general]
targets = ado_scope1

[ado_scope1]
service = azuredevops
ado.PAT = <MyPAT>
ado.project = <MyProject>
ado.organization = <MyOrg>
```

My personal access token has the following permissions :
<img width="409" alt="image" src="https://github.com/ralphbean/bugwarrior/assets/23463958/80b9d877-4ef1-43b0-9ac4-929bc94fcac5">

but when executing the `bugwarrior-pull` I am getting this error message:

```
CRITICAL:bugwarrior.config:
*************************************************
* There was a problem with your bugwarriorrc    *
*   'azuredevops' in [ado_scope1] is not a valid service.
* Here's an example template to help:           *
*************************************************
```

Any ideas what can be the issue root cause ?

**Comment by ryneeverett** [comment]
First issue is that you're looking at the `latest` documentation and not the `stable` documentation, but you're using the `stable` release of bugwarrior. This is an easy pitfall which we're now looking to address in #1007.

I know this because the configuration validation errors are much more helpful in `develop` (#849) and the azuredevops service has not made it into a stable release yet even though it was added a couple years ago (#808).

The winds are starting to suggest we cut a new release fairly soon but I'm afraid I can't give you much of a timeline. A lot of folks use the `develop` branch and that might be the best choice right now if you need azuredevops support.

**Comment by fslef** [comment]
Thanks for your feedback @ryneeverett 

The installed the current bugwarrior instance using the `pip install` command.
I naturally used a `pip uninstall` command to uninstall it, then I tried to reinstall the latest version using the code provided in the doc (excepting I am using a Python3 command)

``` shell
wget https://github.com/ralphbean/bugwarrior/tarball/master -O bugwarrior-latest.tar.gz
tar -xzvf bugwarrior-latest.tar.gz
cd ralphbean-bugwarrior-*
python3 setup.py install
```

I have restarted my terminal but I am still running the same issue.

What can I do next ?

**Comment by ryneeverett** [comment]
The problem I see is that you downloaded the `master` branch, but our development occurs on the `develop` branch.

**Comment by fslef** [comment]
Indeed sorry for the confusion :)

**Comment by fslef** [comment]
That was a good try but I'm still getting an error:

``` shell
Traceback (most recent call last):
  File "/opt/homebrew/bin/bugwarrior-pull", line 33, in <module>
    sys.exit(load_entry_point('bugwarrior==1.8.0', 'console_scripts', 'bugwarrior-pull')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/francoislefebvre/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/francoislefebvre/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/francoislefebvre/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/francoislefebvre/Library/Python/3.11/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bugwarrior-1.7.0-py3.11.egg/bugwarrior/command.py", line 62, in pull
    config = _try_load_config(main_section, interactive)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bugwarrior-1.7.0-py3.11.egg/bugwarrior/command.py", line 35, in _try_load_config
    return load_config(main_section, interactive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bugwarrior-1.7.0-py3.11.egg/bugwarrior/config.py", line 238, in load_config
    validate_config(config, main_section)
  File "/opt/homebrew/lib/python3.11/site-packages/bugwarrior-1.7.0-py3.11.egg/bugwarrior/config.py", line 182, in validate_config
    if not get_service(service):
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bugwarrior-1.7.0-py3.11.egg/bugwarrior/services/__init__.py", line 41, in get_service
    return epoint.load()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2518, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2524, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bugwarrior.services.azuredevops'
```

I'm about to give up on using this tool.
Too bad, it had so much potential, and I was enthusiastic about it.

**Comment by ryneeverett** [comment]
I see now that downloading `master` was an error in our documentation. I'll get that fixed soon.

I'm afraid I can't offer much help as I haven't used ad hoc installation methods like these for a long time. I do recall that I encountered these kinds of issues with outdated entrypoints but I do not recall the solution. Maybe start a new shell?
