### ISSUE TITLE
remove pytest deprecation warnings from develop branch

### ISSUE THREAD

**Issue by bratne** [ralphbean/bugwarrior#1014]
========================================================= warnings summary =========================================================
.env/lib/python3.11/site-packages/taskw/fields/commaseparateduuid.py:9
  /mnt/prm/home/git/github/bugwarrior/.env/lib/python3.11/site-packages/taskw/fields/commaseparateduuid.py:9: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    version = LooseVersion('2.4')

.env/lib/python3.11/site-packages/taskw/warrior.py:573
  /mnt/prm/home/git/github/bugwarrior/.env/lib/python3.11/site-packages/taskw/warrior.py:573: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    return LooseVersion(taskwarrior_version.decode())

.env/lib/python3.11/site-packages/taskw/warrior.py:556
  /mnt/prm/home/git/github/bugwarrior/.env/lib/python3.11/site-packages/taskw/warrior.py:556: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    return cls.get_version() > LooseVersion('2')

**Comment by bratne** [comment]
Nevermind! This is taskwarrior-specific. Closing thing. Removing warnings when using pytest with --disable-warnings instead

**Comment by ryneeverett** [comment]
To clarify, these warnings are in [taskw](https://github.com/ralphbean/taskw).
