### ISSUE TITLE
possibility of setting a date in the configuration file

### ISSUE THREAD

**Issue by cdev92** [ralphbean/bugwarrior#1038]
I'd like to be able to set a date in the configuration file, so that I can only view my mail for the last 3 days.

Sample:

[test.com]
service = gmail
gmail.query = label:in-*vip* AND is:unread AND after:2024-03-10
gmail.thread_limit = 10
gmail.login_name = testt@test.com

I'd like the date to be dynamic,( I can go through an intermediate file and use the awk command with a crontab, but ideally I'd like to be able to use variables natively,  if the used service doesn't allow variables).

**Comment by ryneeverett** [comment]
Looking at [the search api](https://support.google.com/mail/answer/7190), wouldn't `newer_than:4d` be equivalent?

**Comment by cdev92** [comment]
thank you, it works perfectly
