### ISSUE TITLE
Delete tags before adding new ones

### ISSUE THREAD

**Issue by kostajh** [ralphbean/bugwarrior#131]
Currently I'm mapping issue labels in the activeCollab service as Taskwarrior tags. Let's say an activeCollab issue comes in with the label `ON_HOLD`. Bugwarrior creates a TW task with this tag. Then the activeCollab issue gets changed to `IN_PROGRESS`. On the next `bugwarrior-pull` we now have a task with `ON_HOLD` and `IN_PROGRESS` tags assigned.

What do you all think about having Bugwarrior delete any prior tags before assigning them on a task update? /cc @coddingtonbear @ralphbean

**Comment by ralphbean** [comment]
Closing this way after the fact.  :)
