### ISSUE TITLE
Bidirectionality

### ISSUE THREAD

**Issue by techdragon** [ralphbean/bugwarrior#135]
It would be extremely awesome if this tool could have a 'bugwarrior-push' that let you push out local updates to keep other people you may be working on in sync, at the moment, it appears to be import only. So either a documentation update is needed explaining that it can sync both ways, or this is a feature request.

**Comment by ralphbean** [comment]
Respectfully, I'm going to close this feature request.

First off, bugwarrior does not do this now, so we would need to write it.  However even if written, I'd like to not maintain such code either.  I'm too much of a fraidy-cat to push changes to remote issue trackers (which are considered 'authoritative sources' in my world).  I agree it would be awesome though!  If you want to fork bugwarrior and make bugwarrior-nextgeneration to make this happen, I'd cheer you on and buy you a beer.

**Comment by fradeve** [comment]
I agree with @techdragon and @ralphbean at the same time, was thinking about this yesterday. Plus, IMHO the point with a `bugwarrior-push` is that before modifying the source data, we have to download and collect all of the original fields, and this is not done by bugwarrior at now (at least, not for Jira). A lot of fields are missing from the original task, and we don't want to push a modified task/ticket which contains less information than the original one.
