### ISSUE TITLE
Exclude repos for GitHub service does not seem to work

### ISSUE THREAD

**Issue by kostajh** [ralphbean/bugwarrior#141]
In my `.bugwarriorc` I have:

`github.exclude_repos = subDrush,LibTask,task-git,sublime-taskwarrior`

But issues for these repos are added when I run `bugwarrior-pull`. 

Is anyone using the `exclude_repos` option successfully?

**Comment by harleypig** [comment]
I did some experimentation and found that if I included github.{in,ex}clude_repos that these options worked as advertised, but when not including the 'github.' they did not.

**Comment by ralphbean** [comment]
Thanks @harleypig!
