### ISSUE TITLE
Unchanged task gets updated every run

### ISSUE THREAD

**Issue by lmacken** [ralphbean/bugwarrior#151]
Every time I run bugwarrior, even if there are no updates, this message pops up:
```
INFO:db:Updating task (bw)Is#1 - 'LinuxLiveUSBCreator' object has no .. https://github.com/lmacken/liveusb-creator/issues/1; githubtitle: u'LinuxLiveUSBCreator' -> u"'LinuxLiveUSBCreator' object has no attribute 'calculate_liveos_checksum'"
```

**Comment by ralphbean** [comment]
@lmacken, can you try again with the latest task-2.4.1 and bugwarrior-1.1.0 releases?  Things should be working again :pray:.

**Comment by ralphbean** [comment]
OK, I think this one isn't an issue anymore.
