### ISSUE TITLE
adding tasks breaks against task-2.4.0-beta3

### ISSUE THREAD

**Issue by vlabakje** [ralphbean/bugwarrior#176]
Hey,

I'm testing the jira connection and stumbled upon this issue:
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior-1.0.2-py2.7.egg/bugwarrior/command.py", line 49, in pull
TRACE     synchronize(issue_generator, config)
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior-1.0.2-py2.7.egg/bugwarrior/db.py", line 382, in synchronize
TRACE     tw.task_add(**issue)
TRACE   File "/usr/lib/python2.7/site-packages/taskw-0.8.6-py2.7.egg/taskw/warrior.py", line 664, in task_add
TRACE     stderr,
TRACE KeyError: 'Error encountered while creating task;STDOUT: ; STDERR: '

I'm using task-2.4.0-beta3 and that seems to not like supplying a UUID to the task to be added. I've also made a comment in the ticket that caused this, here:
https://bug.tasktools.org/browse/TW-1420

**Comment by ralphbean** [comment]
> I'm using task-2.4.0-beta3

Ah, this is the problem.  We're just not ready for task-2.4.0 yet but are working actively on getting there.  Either use task-2.3.x for now or wait a few weeks until we have a fix for taskw and bugwarrior out.  Thanks!

**Comment by ralphbean** [comment]
FWIW, the latest blocker in porting stuff to task-2.4 is now a new bug in the cli tool:  https://bug.tasktools.org/browse/TW-1498

**Comment by ralphbean** [comment]
Can you test with a fresh install of the latest bugwarrior-1.1.0 and taskwarrior-2.4.1?   Everything should be working now :pray:.

**Comment by mekanix** [comment]
I've installed from git and bugwarrior does the job of syncing but it errors on (un)locked file:
```bash
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/home/meka/.virtualenvs/v/local/lib/python2.7/site-packages/bugwarrior/command.py", line 64, in pull
TRACE     lockfile.release()
TRACE   File "/home/meka/.virtualenvs/v/local/lib/python2.7/site-packages/lockfile/pidlockfile.py", line 106, in release
TRACE     raise NotLocked("%s is not locked" % self.path)
TRACE NotLocked: /home/meka/.task/bugwarrior.lockfile is not locked
```

**Comment by ralphbean** [comment]
That's... surprising.  Can you remove that file and try again?

Also, what platform are you on?  Linux?  Mac?

**Comment by mekanix** [comment]
Sorry for disturbing, it was [Mirakel](https://github.com/MirakelX/mirakel-android) sending gibberish. I think it's 2.3 vs 2.4 "thingie". In [your comment](https://github.com/ralphbean/bugwarrior/issues/176#issuecomment-74616422) you said you solved something similar. Can you point to pull request or the files or whatever you did to become taskwarrior 2.4 ready? I'd like to try to fix it for Mirakel, too. Thank you!

**Comment by ralphbean** [comment]
@mekanix it was mostly here in ralphbean/taskw#68.

I'm going to close this since I think the original issue reported by @vlabakje was resolved.
