### ISSUE TITLE
trac not well-formed (invalid token) error

### ISSUE THREAD

**Issue by jouty** [ralphbean/bugwarrior#177]
Hi, i fall on this error when trying to pull trac tickets

CRITICAL:my_trac:Worker for [my_trac] failed: not well-formed (invalid token): line 28, column 5
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/**init**.py", line 461, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/trac.py", line 117, in issues
TRACE     tickets = map(self.trac.get_ticket, tickets)
TRACE   File "/usr/lib/python2.7/site-packages/offtrac/__init__.py", line 69, in get_ticket
TRACE     return self.server.ticket.get(ticket)
TRACE   File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in **call**
TRACE     return self.__send(self.__name, args)
TRACE   File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
TRACE     verbose=self.__verbose
TRACE   File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
TRACE     return self.single_request(host, handler, request_body, verbose)
TRACE   File "/usr/lib64/python2.7/xmlrpclib.py", line 1297, in single_request
TRACE     return self.parse_response(response)
TRACE   File "/usr/lib64/python2.7/xmlrpclib.py", line 1467, in parse_response
TRACE     p.feed(data)
TRACE   File "/usr/lib64/python2.7/xmlrpclib.py", line 557, in feed
TRACE     self._parser.Parse(data, 0)
TRACE ExpatError: not well-formed (invalid token): line 28, column 5
INFO:my_trac:Done with [my_trac] in 20.245192s
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/command.py", line 49, in pull
TRACE     synchronize(issue_generator, config)
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 335, in synchronize
TRACE     raise RuntimeError(issue[1])
TRACE RuntimeError: not well-formed (invalid token): line 28, column 5

conf file : 
[my_trac]
service = trac
trac.base_uri = trac.mydomain.net/infra
trac.scheme = https
trac.username = jouty
trac.password = mypassword

**Comment by ralphbean** [comment]
First question, what version of the ``task`` cli do you have installed?

**Comment by jouty** [comment]
hi,

python-taskw-0.8.6-1.fc21.noarch
task-2.3.0-2.fc21.x86_64
============================
Trac 	0.12.1
TracXMLRPC 	1.1.2

**Comment by ralphbean** [comment]
Hm, that all looks good.

It looks like a bug either in the way your trac instance is set up, or in the ``python-offtrac`` module that ``taskw`` uses to talk to your instance, although I can't be sure without trying to mess around with it directly.

- Do you have any other tools that interface with your xmlrpc plugin there?  Do they work?
- Can you mess around with offtrac directly in a python shell and try yourself to connect?

**Comment by jouty** [comment]
With xmlrpc directly :
>>> from xmlrpclib import ServerProxy
In [28]: server = xmlrpclib.ServerProxy("https://jouty:password@trac.mydomain.net/infra/login/xmlrpc")
In [29]: server.system.getAPIVersion()
Out[29]: [1, 1, 2]

Now with offtrac
In [61]: import sys

In [62]: import urllib
In [63]: trac = TracServer('https://jouty:mypassword@trac.mydomain.net/infra/login/xmlrpc')
In [64]: trac.get_ticket('2894')
Out[64]: 
[2894,
 <DateTime '20140718T11:07:43' at 7f929a9a5bd8>,
 <DateTime '20140820T09:40:25' at 7f929a9a5680>,
 {'_ts': '2014-08-20 09:40:25.269523+00:00',
  'blockedby': '',
  'blocking': '',
  'changetime': <DateTime '20140820T09:40:25' at 7f929a9a5c20>,
  'complete': '0',
  'resolution': '',
  'severity': 'regular',
  'status': 'new',
etc

**Comment by ralphbean** [comment]
wow.  there must be something malformed about the way bugwarrior is constructing that url for ``TracServer`` but I don't see anything obvious in the bugwarrior trac service at first glance:

https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/trac.py#L71-L94

**Comment by jouty** [comment]
i have search too but don't found

**Comment by ralphbean** [comment]
@jouty, I'm cleaning up the issue queue and am going to close this.

If this is still affecting you and is something you'd like to see fixed, please feel free to re-open it or file a new issue.
