### ISSUE TITLE
The expression could not be evaluated (task-2.4.0-1)

### ISSUE THREAD

**Issue by bmbove** [ralphbean/bugwarrior#181]
After upgrading taskwarrior to 2.4.0-1, I receive the following when running bugwarrior-pull:

>INFO:bugwarrior:Service-defined UDAs (you can optionally add these to your ~/.taskrc for use in reports):
>INFO:bugwarrior:uda.tracurl.type=string
>INFO:bugwarrior:uda.tracurl.label=Trac URL
>INFO:bugwarrior:uda.tracnumber.type=numeric
>INFO:bugwarrior:uda.tracnumber.label=Trac Number
>INFO:bugwarrior:uda.tracsummary.type=string
>INFO:bugwarrior:uda.tracsummary.label=Trac Summary
>CRITICAL:command:oh noes
>TRACE Traceback (most recent call last):
>TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/command.py", line 49, in pull
>TRACE     synchronize(issue_generator, config)
>TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 330, in synchronize
>TRACE     'closed': get_managed_task_uuids(tw, key_list, legacy_matching),
>TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 108, in get_managed_task_uuids
>TRACE     ('status', 'waiting'),
>TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 590, in filter_tasks
>TRACE     *query_args
>TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 489, in _get_task_objects
>TRACE     json = self._get_json(*args)
>TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 484, in _get_json
>TRACE     encoded = self._execute(*args)[0]
>TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 479, in _execute
>TRACE     raise TaskwarriorError(command, stderr, stdout, proc.returncode)
>TRACE TaskwarriorError: ['task', 'rc:/home/brian/.taskrc', 'rc.uda.tracurl.type=string', 'rc.uda.tracurl.label="Trac URL"', 'rc.uda.tracnumber.type=numeric', 'rc.uda.tracnumber.label="Trac Number"', 'rc.uda.tracsummary.type=string', 'rc.uda.tracsummary.label="Trac Summary"', 'rc.json.array=TRUE', 'rc.confirmation=no', 'rc.verbose=nothing', 'export', '(tracurl.not:"")', '(status:"pending" or status:"waiting")'] #2; stderr:"The expression could not be evaluated."; stdout:""

Downgrading to task-2.3.0-4 seemed to fix this. I've played around with taskwarrior, and it seems to be related to this change in e9bdb67:

    1169|     : - rhs.attribute ("raw", value);
         |1170: + rhs.attribute ("raw", "'" + value + "'");

https://github.com/taskwarrior/task/commit/e9bdb6704ffa0d388b3e7e7d40844325d097e5b6#diff-5dd069e991ecb94bdf07ac7e0f499470R877

Changing that line back makes bugwarrior work just fine. I'm wasn't sure if it was a problem with taskwarrior, or if bugwarrior needs to be adapted to this change; I don't know enough about the filter syntax to make that call. Looking at that change though, it seems it makes it impossible to check for an empty value, as a ("") is going to be quoted again, and it it doesn't seem to accept something like "(tracurl.not:)".

**Comment by bmbove** [comment]
Changing (tracurl.not:"") to (tracurl.any) also works for that particular filter.

**Comment by ralphbean** [comment]
Cool - I ran into the same thing but couldn't find a workaround.. I ended up filing a bug on taskwarrior here -> https://bug.tasktools.org/browse/TW-1498

Can you submit that as a pull request?

**Comment by ralphbean** [comment]
Ah, yeah.  That's the problem (now that I think about it).

Your workaround works for trac because the primary UDA trac uses is ``tracurl``, a string-type UDA.

Other backends use *numeric* UDAs, and as mentioned in TW-1498, those are still broken in task-2.4.0.

**Comment by bmbove** [comment]
A pull request on here or the one for taskwarrior? The taskwarrior change I assume was purposeful for whatever rework went into 2.4.0. Just confused by the order of your comments I suppose. I only use trac, so I didn't dig deep enough to find out, but would changing that filter string in bugwarrior affect anything with a numeric UDA?

**Comment by ralphbean** [comment]
Sorry to not be clear.

- Could you submit your patch on bugwarrior?
- It should get things working for services with non-numeric UDAs (like trac).  Other services with numeric UDAs will still be broken until the task-2.4.1 release comes out (ETA January 15th).

**Comment by ralphbean** [comment]
OK.  task-2.4.1 is out and with it, bugwarrior-1.1.0.  This should all be working now.
