### ISSUE TITLE
[JIRA] Docs are not detailed enough about queries and usernames

### ISSUE THREAD

**Issue by fradeve** [ralphbean/bugwarrior#186]
While experimenting with Bugwarrior (thanks for giving us such useful tool) I noticed that the default query

    assignee = ralph and status != closed and status != resolved

will not work if the `status` in your JIRA instance is capitalized. E.g., in my case I have `Done`, `Resolved`, `Closed`, and this query has done the trick:

    jira.query = assignee = 'francesco.devirgilio' and status != Closed and status != Resolved and status != Done

As you can see, I've also had to modify the username if it contains complex characters (a dot in my case).
It would be nice to specify all these details in the docs, so that the user is aware of this and will not spend too much time to figure out why the default query doesn't fit.

I can open a pull request if you want :)

**Comment by coddingtonbear** [comment]
I think a pull request might be best; let me know, though, if you're too busy, I'm sure @ralphbean or I can find the time, if so.

**Comment by fradeve** [comment]
No worries, I will create a pull request :dancer:

**Comment by ralphbean** [comment]
> No worries, I will create a pull request :dancer:

Awesome!

**Comment by fradeve** [comment]
https://github.com/ralphbean/bugwarrior/pull/187

**Comment by fradeve** [comment]
#187 merged, think we can close this :)
