### ISSUE TITLE
Allow setting a different configuration file

### ISSUE THREAD

**Issue by mathstuf** [ralphbean/bugwarrior#189]
I use two task lists, one for personal and another for work. It would be nice to be able to have bugwarrior pull into each one separately. I can think of two ways to do this:

  - add a flag to bugwarrior to specify the configuration file (which I can alias away); or
  - allow multiple `[general]` configuration sections with separate `taskrc` values and `targets` listings.

**Comment by ralphbean** [comment]
Ah.. let's go with the first option and add a flag.  :)
