### ISSUE TITLE
bitbucket OAuth

### ISSUE THREAD

**Issue by mathstuf** [ralphbean/bugwarrior#201]
Should probably use OAuth as well.

**Comment by ryneeverett** [comment]
I looked into implementing this, but was disappointed at what I found:

- [Bitbucket's OAuth2 implementation requires basic authentication to get a temporary token.](https://bitbucket.org/site/master/issues/11520/oauth-2-authentication-does-not-work)
- [Bitbucket's OAuth1 implementation requires browser login to get a temporary token.](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Step3.Redirecttheusertotoauthorizeyourapplication)

My primary motivation to implement this was to avoid needing to provide bugwarrior a password, but OAuth2 doesn't solve that. And web browser login on every `bugwarrior-pull` is obviously not an option.

**Comment by ryneeverett** [comment]
For future reference though, requests_oauthlib has [a Bitbucket OAuth1 tutorial](http://requests-oauthlib.readthedocs.org/en/latest/examples/bitbucket.html).

**Comment by ryneeverett** [comment]
I knew I had to be wrong about this so I kept digging. You can get [a refresh token](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Refreshtokens):

> Most access token grant response therefore include a refresh token that can then be used to generate a new access token, without the need for end user participation

So I guess we could prompt for a password on first usage and thereafter use the refresh token.

**Comment by ryneeverett** [comment]
Bugwarrior doesn't seem to persist any data of its own currently, so I think we'd need to add a `~/.task/bugwarrior.data` file, per [the third-party guidelines](https://taskwarrior.org/docs/3rd-party.html#guidelines):

> If you need to store additional data, consider putting your own data file in the `~/.task` directory. Just don't use the file names `pending.data`, `completed.data`, `backlog.data`, or `undo.data`.
