### ISSUE TITLE
Bitbucket improvements

### ISSUE THREAD

**Issue by mathstuf** [ralphbean/bugwarrior#202]
It would be nice to be able to give a list of usernames for github and bitbucket services rather than making a block per organization. It would also be nice to be able to pull any issue or pull request I'm involved in (watching, filed, assigned, etc.) regardless of the user.

**Comment by mathstuf** [comment]
It actually appears there's no API endpoint for this stuff yet :( .

**Comment by mathstuf** [comment]
I requested for GitHub by the way. Bitbucket's issue tracker is drowning in requests anyways and I have no idea what their plan is with making APIv2 actually useful, so ignoring them for now.

**Comment by mathstuf** [comment]
So this could be hacked up with github's search API, but only for issues. If we're lucky, a real API endpoint will be added.

**Comment by ralphbean** [comment]
Hm.  One aspect of this is that sometimes you want different config options for different github usernames/organizations.

For instance, I want *all* issues on all of my personal repos to be synced.  But, on some organization I'm a part of, perhaps I only want all the issues that are *assigned to me*.

If you listed them in the same block, I can't think of a good way to specify which options should be assigned to which user/org.

**Comment by mathstuf** [comment]
The idea is that a block fetches all assigned/watched/filed issues and pull requests. Adding a blacklist based on org/user shouldn't be too bad on top of that.

**Comment by mathstuf** [comment]
Github is fixed by #234 at least.

**Comment by mathstuf** [comment]
The `github` label can be removed here; that bit is implemented.

**Comment by ryneeverett** [comment]
Triage: This is currently the oldest issue and hasn't been touched for a while. It seems like it's been mostly resolved. If there's still something wanted here it would be better to open a new issue of more focused scope at this point.
