### ISSUE TITLE
Support for Mantis

### ISSUE THREAD

**Issue by mathstuf** [ralphbean/bugwarrior#204]
_sigh_ As much as I dislike it, seems it won't just disappear :/ . It uses SOAP which seems to have had iffy support in Python (at least historically). Happy for someone else to tackle this, but I imagine I will at some point if/when the lack of it becomes annoying enough.

**Comment by mathstuf** [comment]
Well, we're finally getting rid of Mantis (party!), so I have no interest in implementing this.

**Comment by evmcl** [comment]
FYI, MantisBT now has a REST based [API](https://mantisbt.org/docs/master/en-US/Admin_Guide/html-desktop/#admin.config.api) available.

**Comment by ssbarnea** [comment]
While I do not use mantis too often I still have few Mantis instances that I want to ocassionaly check that are using it. In my case is https://bugs.centos.org which is still using Mantis with no known plans to ditch it AFAIK.

**Comment by ralphbean** [comment]
Going to close this (cleaning up the queue). See also #410 for anyone who wants to contribute this as a patch.
