### ISSUE TITLE
Can't connect with Jira on Atlassian cloud

### ISSUE THREAD

**Issue by Crawleyprint** [ralphbean/bugwarrior#211]
I've tried to connect to Jira instance on atlassian's service (https://org-name.atlassian.net) and it keeps throwing me 'unauthorized' error. I've noticed that they have Jira 6.4 and there is only mention fo Jira 4 and 5 in the docs. Is Jira 6 supported or it has something to do with atlassian cloud login?

One other thought is that I've added wrong base uri, here is the format, can anyone confirm it's correct?

    jira.base_uri = https://<org-name>.atlassian.net

**Comment by ralphbean** [comment]
@ubuntudroid @nikolavp @coddingtonbear, can any of you comment on this?

**Comment by ubuntudroid** [comment]
@Crawleyprint Try adding

```jira.verify_ssl = False```

to your jira configuration.

**Comment by Crawleyprint** [comment]
@ubuntudroid  I've tried both with and without, still says it's unauthorized

**Comment by Crawleyprint** [comment]
it's Jira v6, I have to stress that once more.

**Comment by fradeve** [comment]
Hi @Crawleyprint, please take a look to #186. I'm using 1.0.2 with JIRA 6 and it is working fine.

**Comment by kostajh** [comment]
@Crawleyprint I'm using this with Jira 6. Make sure your username is correct (the name that pops up when someone does an @ mention for you).

**Comment by Crawleyprint** [comment]
@kostajh thanks, I was entering wrong username all the time, it's different from login name, which has an email in it (facepalm)...

**Comment by ralphbean** [comment]
[![Problem solved!](http://img.youtube.com/vi/e3mLoFndR6M/0.jpg)](http://www.youtube.com/watch?v=e3mLoFndR6M)

**Comment by ytjohn** [comment]
I came across this when I had issues. Just adding a note that v6 enables a captcha by default. So if you get 403s, use a web browser to log out and then back in, solving the captcha. Then try bugwarrior-pull  again.

**Comment by jakebrinkmann** [comment]
FYI for the future person using Single Sign On (SSO):

```
[my_jira]
service = jira
jira.base_uri = http://<my-org>.atlassian.net
jira.username = <my-email>@<my-org>.com
jira.password = <API Token>
```

Maybe it's obvious 🤷
