### ISSUE TITLE
Pulling JIRA tasks logs out the web user

### ISSUE THREAD

**Issue by GaretJax** [ralphbean/bugwarrior#212]
When pulling the tasks from JIRA (a cloud instance, in my case), the web user session (the one I use in the browser) is logged out. I had the same issue when developing a tool for myself and discovered that it is due to the `jira` package sending cookies along with requests.

I have solved it this way: https://github.com/GaretJax/lancet/blob/f175cb2ec9a2135fb78188cf0b9f621b51d88977/lancet/jira.py#L10-L17 and https://github.com/GaretJax/lancet/blob/f175cb2ec9a2135fb78188cf0b9f621b51d88977/lancet/jira.py#L24-L27

**Comment by ralphbean** [comment]
Are you still hitting this issue @GaretJax?  I've never encountered it myself.

**Comment by Fongshway** [comment]
This may actually be a non-issue now given [Deprecation of basic authentication with passwords for Jira and Confluence APIs](https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html). [Api tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html) are now the preferred way to authenticate a script.

**Comment by ralphbean** [comment]
Ack.  Let's close this then.  @GaretJax, if we're wrong - please re-open!

**Comment by GaretJax** [comment]
I guess it's ok. It has anyway always been a bug on the JIRA side of things.
