### ISSUE TITLE
kanboard support

### ISSUE THREAD

**Issue by jasonsmith0** [ralphbean/bugwarrior#223]
Would be great if this project expanded and added support for another great open source tool - kanboard www.kanboard.net .

Nice to have for visualisation and kanban methodology while still using task to manage it.

API: http://kanboard.net/documentation/api-json-rpc

I unfortunately don't have the skills to do this.

**Comment by jasonsmith0** [comment]
Though kanban supports integration with gitlab/github so perhaps one could already get this to work.

**Comment by coddingtonbear** [comment]
I know this is just a *little* tangential, but if you were mostly just looking for Kanban functionality (rather than using that specific service), you could try Inthe.AM's Trello integration.

**Comment by jasonsmith0** [comment]
Cool thanks for the tip. Maybe for someone else, but for me I like to keep data in house for privacy reasons.

**Comment by jasonsmith0** [comment]
Bug cross filed.
https://github.com/fguillot/kanboard/issues/990

**Comment by ralphbean** [comment]
Going to close this (cleaning up the queue). See also #410 for anyone who wants to contribute this as a patch.
