### ISSUE TITLE
Please implement 'only_if_assigned' option for Bugzilla plugin

### ISSUE THREAD

**Issue by thozza** [ralphbean/bugwarrior#243]
Currently it is not possible to filer bugs from Bugzilla based on the assignee. The result is that also bugs not assigned to me, but reported by me are added to my tasks in taskwarrior. It would be nice to be able to filter only bugs assigned to me.

**Comment by ralphbean** [comment]
Yeah, the ``get_owner`` method in the bugzilla issue service just has ``raise NotImplementedError``, so we'd need to start there and then leverage the ``.include(...)`` method somewhere in there too.

**Comment by Mte90** [comment]
Waiting for this one a lot, there are updates since this ticket?

**Comment by Mte90** [comment]
I tried now changing that line https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/bz.py#L225 with my `email` but didn't worked.

Looking if I can do that with a query

**Comment by Mte90** [comment]
Got it with the query_url:
`bugzilla.query_url = https://bugzilla.mozilla.org/query.cgi?query_format=advanced&short_desc_type=allwordssubstr&short_desc=&bug_status=ASSIGNED&longdesc_type=allwordssubstr&longdesc=&bug_file_loc_type=allwordssubstr&bug_file_loc=&status_whiteboard_type=allwordssubstr&status_whiteboard=&keywords_type=allwords&keywords=&bug_id=&bug_id_type=anyexact&votes=&votes_type=greaterthaneq&emailassigned_to1=1&emailtype1=exact&email1=mte90net@gmail.com&emailtype2=substring&email2=&emailtype3=substring&email3=&chfieldvalue=&chfieldfrom=&chfieldto=Now&j_top=AND&f1=noop&o1=noop&v1=`
