### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by ralphbean** [ralphbean/bugwarrior#25]
Use python-modernize and 'six'

**Comment by ryneeverett** [comment]
At this point, is there any reason to maintain python2 support when we do this? We're halfway to the 2020 EOL since this issue was opened and as far as I know every distro ships with python3.

**Comment by mathstuf** [comment]
Bugwarrior is an end-user application, so I don't think there's any "but dependencies care about the Python" version problems.

**Comment by coddingtonbear** [comment]
I am using bugwarrior as a library in Inthe.AM, but, really, don't worry about me; I'll adapt if you drop Python 3 support.

**Comment by ralphbean** [comment]
+1 from me to go all-in with python3, with condolences to @coddingtonbear.

**Comment by irl** [comment]
As I've packaged dependencies in Debian, I've made sure to build both Py 2 and Py 3 versions for them. Going pure Py 3 should be an easy transparent switch to end users when it happens.

**Comment by ryneeverett** [comment]
Closing, even though there are no doubt plenty of python3 incompatibilities yet to be found. Now that the test suite supports python3, compatibility bugs may be reported in separate issues.

For the record, it looks like we'll be supporting python2 indefinitely. Supporting both versions doesn't seem to be that big of a deal and there's no reason to break compatibility without benefit.
