### ISSUE TITLE
Allow self signed certificates for Gitlab service

### ISSUE THREAD

**Issue by muxync** [ralphbean/bugwarrior#257]
When using a self signed certificate with the Gitlab service I get the following error:
```
CRITICAL:gitlab|Worker for [gitlab] failed: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

I'm using Linux Mint 17.2 Rafaela and was able to get this working by upgrading python requests
```
sudo pip install requests --upgrade
```

and by modifying gitlab.py as follows
```diff
git diff HEAD^ HEAD
diff --git a/bugwarrior/services/gitlab.py b/bugwarrior/services/gitlab.py
index d470c65..08f2d77 100644
--- a/bugwarrior/services/gitlab.py
+++ b/bugwarrior/services/gitlab.py
@@ -8,6 +8,8 @@ from twiggy import log
 from bugwarrior.config import asbool, die, get_service_password
 from bugwarrior.services import IssueService, Issue
 
+import requests.packages.urllib3
+requests.packages.urllib3.disable_warnings()
 
 class GitlabIssue(Issue):
     TITLE = 'gitlabtitle'
@@ -274,7 +276,7 @@ class GitlabService(IssueService):
         url = tmpl.format(scheme=self.scheme, host=self.auth[0])
         headers = {'PRIVATE-TOKEN': self.auth[1]}
 
-        response = requests.get(url, headers=headers, **kwargs)
+        response = requests.get(url, headers=headers, verify=False, **kwargs)
 
         if callable(response.json):
             json_res = response.json()
```
This is currently not worthy of a pull request but I'm happy to submit a proper PR if this is a feature that would be merged.  Would adding a configuration option like 'gitlab.self_signed_cert' be an acceptable implementation?

**Comment by ralphbean** [comment]
How about `gitlab.verify_ssl` for the option name?  `self_signed_cert` could be misleading, since people might think that we will actually verify that the self-signed-cert is in their trust root or something (which is not the case here).

I'm cool with the implementation though.  Thanks!

**Comment by muxync** [comment]
Good point about ```self_signed_cert```.  Hopefully PR #261 implements ```verify_ssl``` as expected.  Thanks!
