### ISSUE TITLE
error 500: Unrecognized taskwarrior file format

### ISSUE THREAD

**Issue by ersanchez** [ralphbean/bugwarrior#268]
Hi, I keep getting this error message:
`Sync failed. The Taskserver returned error: 500 Unrecognized taskwarrior file format.` 
Can anyone provide steps to fix this? I can't find anything searching Google or here.
Thanks

**Comment by ersanchez** [comment]
Sorry, I just read about including the results of `task diagnostics` in my request for help.

****

task 2.5.0
   Platform: Linux

Compiler
    Version: 4.9.2
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov 14 2015 08:57:32
      CMake: 3.0.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.3.8
 Build type: 

Configuration
       File: /home/ers/.taskrc (found), 1848 bytes, mode 100664
       Data: /home/ers/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: taskwarrior.inthe.am:53589
         CA: /home/ers/Dropbox/taskwarrior/foo-bar/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: /home/ers/Dropbox/taskwarrior/foo-bar/private.certificate.pem, readable, 2462 bytes
        Key: /home/ers/Dropbox/taskwarrior/foo-bar/private.key.pem, readable, 3664 bytes
    Ciphers: NORMAL
      Creds: inthe_am/foo-bar/************************************

Hooks
    Scripts: Enabled
             (-none-)

Tests
      $TERM: xterm-256color (120x63)
       Dups: Scanned 324 tasks for duplicate UUIDs:
             No duplicates found

**Comment by ersanchez** [comment]
Ok, I found a work-around to restore my synchronization. 

Running:
`$ task rc.debug=1 rc.debug.tls=2 sync` 
as described in the **Debugging** section of [Troubleshooting Sync][ts] I noticed that there were three line items that had dependencies. By deleting these items in $HOME/.task/backlog.data I was able to get the sync to work again. 
Next, I edited each of the line items to remove dependencies: `$ task 123 modify depends:   ` 
This let me mark the tasks as complete and then successfully sync.

I think there might be an issue with line items that have dependencies. I'm not sure what the fix is. 

In my case the line item that the tasks depended on had been completed. There should be some mechanism to remove the dependencies once the "master" item is done.

Example:

`122 buy new hard drive`
`123 depends:122 install new hard drive`

`$ task 122 done`

This should change 123 to `depends:  `  since the dependency no longer exists, no?



[ts]:https://taskwarrior.org/docs/taskserver/troubleshooting-sync.html

**Comment by gdetrez** [comment]
@ersanchez this doesn't seem to have anything to do with bugwarrior. To get help, or report bug against taskwarrior, you can look at http://taskwarrior.org/support/.

**Comment by ersanchez** [comment]
Closing the issue - mistakenly posted this in the wrong forum.

**Comment by sanjayankur31** [comment]
Reported here: https://bug.tasktools.org/browse/TD-104

Feel free to add more info. It does indeed look like an issue with "depends".
