### ISSUE TITLE
Github pull-request filtering did not filter the PRs out

### ISSUE THREAD

**Issue by gfrivolt** [ralphbean/bugwarrior#278]
Based on the docs I added `github.filter_pull_requests = True` to the service group for github but it did not work.

**Comment by gdetrez** [comment]
@gfrivolt What did expect to happen and what did actually happen?
See also #315.

**Comment by gfrivolt** [comment]
sorry, I see that I was't specific. I'd expect that pull request would not show up, they would not be pulled, when `github.filter_pull_requests = True`.

**Comment by gdetrez** [comment]
Interesting, I had a different interpretation of the option description (but I'm not sure which one is the originally intended one...)

**Comment by ryneeverett** [comment]
While the option might not be semantically ideal, I think the documentation is pretty clear.
