### ISSUE TITLE
Private github tasks are not pulled

### ISSUE THREAD

**Issue by gfrivolt** [ralphbean/bugwarrior#282]
I've create a token with `repo`, Full control of private repositories, scope. When I access the github API using `curl` I get what I expect, the issues for the private repo I retrieved.

I used that: `curl -u fifigyuri:<token> https://api.github.com/repos/netronixgroup/environet-ui/issues`

And I've got the list of private repo's issues. But bugwarrior does not load these issues for me. This is my config file:

```
[general]
targets = netronix_github
taskrc = ~/.taskrc
shorten = True
annotation_links = True

[netronix_github]
service = github
project_template = {{project|lower}}
description_template = {{githubnumber}}: {{githubtitle}}
github.username = netronixgroup
github.login = fifigyuri
github.token = <token>
github.import_labels_as_tags = True
github.label_template = gh-{{label}}
github.filter_pull_requests = True
```

The public issues I have are pulled, but I'd like to see the private ones only. What went wrong? Where did I make a mistake? Thank you for your help!

**Comment by ryneeverett** [comment]
Do the private repositories belong to `fifigyuri` rather than `netronixgroup`? If so I'm guessing you'd have to add it to `github.username`. Just my initial thought.

**Comment by fifigyuri** [comment]
no, I login in as `fifigyuri`, the account is `netronixgroup`. I tried to switch the values or `github.username` and `github.login`, did not help

**Comment by ryneeverett** [comment]
Hmm, does `curl -u fifigyuri:<token> https://api.github.com/users/netronixgroup/repos` include the private repos? Bugwarrior basically just calls that to get the list of repos and then loops over it with the curl command you already said works.

**Comment by fifigyuri** [comment]
It lists the public repositories for the account. Seems like issue with the token, but I have `repo` scope set.

![edit_personal_access_token](https://cloud.githubusercontent.com/assets/98457/12748583/7d071294-c9ab-11e5-8037-7ddac2a6b73a.jpg)

**Comment by fifigyuri** [comment]
I found that, bit disturbing things about github API: http://stackoverflow.com/questions/21907278/github-api-using-repo-scope-but-still-cant-see-private-repos

I tried to call `curl -u fifigyuri:<token> https://api.github.com/user/repos` and it returned me private repos.

If bugwarrior calls `GET /users/someusername/repos` for retrieving repos and should not return any private ones.

**Comment by ryneeverett** [comment]
Nice, you've identified the problem. I think the solution would be to call `https://api.github.com/user/repos` rather than `https://api.github.com/users/{username}/repos` and then filter out the ones that aren't owned by a `github.username`.

**Comment by andrea-imparato-sociomantic** [comment]
I would also need this feature. Tell me if I can help in any way.

**Comment by ryneeverett** [comment]
Give #323 a try.

**Comment by ryneeverett** [comment]
Ah, I'd forgotten about the need to pull private issues owned by orgs other than the user, which is why I think my above comment is correct:

>  think the solution would be to make a call to https://api.github.com/user/repos and then filter out the ones that aren't owned by github.username.

**Comment by ryneeverett** [comment]
I tried again in #324.

**Comment by ryneeverett** [comment]
@andrea-imparato-sociomantic you can help by testing out #324. Simplest way is `pip install git+https://github.com/ryneeverett/bugwarrior.git@fix-github-private-repos#egg=bugwarrior`.

**Comment by andrea-imparato-sociomantic** [comment]
you probably missed the `--upgrade` in the command line parameters :). Anyway checking it out now :+1:

**Comment by ryneeverett** [comment]
@andrea-imparato-sociomantic Yeah, I should have included that. I just tested in a temporary virtualenv so I didn't need it.

**Comment by xeor** [comment]
Sorry for commenting on an old issue.. But when will this fix hit the main pip package? We are getting `1.4`, which doesnt contain this fix.

**Comment by ryneeverett** [comment]
Next release. See #339.
