### ISSUE TITLE
RFE: sync from a calendar

### ISSUE THREAD

**Issue by ralphbean** [ralphbean/bugwarrior#297]
Perhaps an ical export or any other API google calendar exposes.

It would be nice to have my meetings for the day peppered in my task list and noted in my status reports.

**Comment by ryneeverett** [comment]
Did you see [the perl ical export script](http://taskwarrior.org/download/export-ical.pl)?

To me this seems pretty out of scope for bugwarrior. It isn't particularly related to bug tracking so I don't see the advantage of having it in the code base. There shouldn't be anything in bugwarrior abstract enough to help with this feature. If there is, perhaps we should push it upstream into taskw?

**Comment by coddingtonbear** [comment]
I think @ralphbean is referring, rather, to importing calendar events as tasks (rather than the other way around), @ryneeverett.  I'm not sure I have a philosophical objection to such a feature being added here -- I think of bugwarrior as more of a "taskwarrior integration engine" than a "taskwarrior bug tracking tool" -- but there are advantages to keeping a package's mission concise.

**Comment by ryneeverett** [comment]
> I think @ralphbean is referring, rather, to importing calendar events as tasks (rather than the other way around), @ryneeverett.

Good point, that link is irrelevant.

**Comment by ralphbean** [comment]
Yeah - I was thinking of importing calendar events as tasks.

If anyone here is opposed to the scope creep, I wouldn't mind carrying it as a private plugin.

**Comment by ryneeverett** [comment]
Well I looked through the taskwarrior "tools" list and was surprised to learn that bugwarrior seems to be the only package in the "synchronize tasks with web service API's" category. So expanding scope to fill this entire category might not be unreasonable. I'm -0.

**Comment by ralphbean** [comment]
Eh, my personal use case for this fell apart - to get at my work calendar we'd have to do a great big heavyweight oauth2 dance with an OTP token.  Not worth it.  Closing as wontfix.  :)

**Comment by ralphbean** [comment]
I'm re-opening this.  I've had a change of heart.  :)

**Comment by seniorivn** [comment]
@ralphbean any updates?

**Comment by ralphbean** [comment]
None yet.  (except that @dgregor expressed interest in this too... ;p)

**Comment by ryneeverett** [comment]
Going to close this (cleaning up the queue). However, do see #410 for anyone who wants to contribute this as a patch.

For the record though, I'm still not entirely sure this could be abstract enough to meet enough use cases to be maintained as part of bugwarrior. At the very least though it would be a good candidate as a plugin (#775).
