### ISSUE TITLE
OTRS support

### ISSUE THREAD

**Issue by 4001982248998** [ralphbean/bugwarrior#311]
TW and OTRS user here. I was exited to find out bugwarrior exists, and disappointed that OTRS is not supported. Unfortunately, I do not have the skills to develop the service support by myself.

Any chance of making OTRS a supported service?

**Comment by ralphbean** [comment]
Sure!  But.. we have to have someone who 1) uses [otrs](https://www.otrs.com/) and 2) can develop the plugin, otherwise we don't have a good way to support it long term.

We try to rely on people to become maintainers of the different backend plugins (I don't use all of them myself), otherwise they suffer bit rot over time.

Would definitely accept a patch to support OTRS.  :)

**Comment by svenehret** [comment]
did I miss any documentation for plugin development? I might have a look at it.

**Comment by ryneeverett** [comment]
> Unfortunately, I do not have the skills to develop the service support by myself.

Don't be so sure about that. We can't lead development, but we can guide and help.

> did I miss any documentation for plugin development? I might have a look at it.

I don't think so, but do see http://bugwarrior.readthedocs.io/en/latest/contributing.html. Guiding you through this process may be a good opportunity to develop a guide for adding a new service.

**Comment by ryneeverett** [comment]
One thing I did notice was missing from the docs is that you should create a new branch based off of our develop branch, e.g.

```sh
(bugwarrior)$ git checkout -b otrs-service develop
```

**Comment by eliasp** [comment]
It would probably make sense to use [OTRS' GenericInterface](https://otrs.github.io/doc/manual/admin/5.0/en/html/genericinterface.html) and ship a REST-based WebService configuration for it which provides exactly the data/interfaces Bugwarrior needs.

**Comment by ralphbean** [comment]
Going to close this (cleaning up the queue). See also #410 for anyone who wants to contribute this as a patch.
