### ISSUE TITLE
An option for "assigned issues"

### ISSUE THREAD

**Issue by gdetrez** [ralphbean/bugwarrior#314]
In the github service, assigned issues are added to TW unconditionally. Shouldn't they also respect constraint such as `include_repos` and `exclude_repos`? Or maybe there should be an option to have all assigned issues *in addition* to the other pulled issues.

**Comment by ryneeverett** [comment]
I suspect the current behavior is due to *everyone wanting to unconditionally pull all issues assigned to them*. I'm curious why you don't want this.

**Comment by gdetrez** [comment]
I have two task lists, one at work and one at home, both pulling tasks from github but from different repositories. I don't want issues from my personal project ending in my work list and vice versa.

**Comment by ryneeverett** [comment]
Ah, makes sense.
