### ISSUE TITLE
cannot pull issues from bitbucket

### ISSUE THREAD

**Issue by discipolo** [ralphbean/bugwarrior#326]
neither private nor public.

failed: Non-200 status code 401
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 502, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/bitbucket.py", line 212, in issues
TRACE     response = self.get_data('/repositories/' + user + '/')
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/bitbucket.py", line 155, in get_data

is bitbucket supposed to be working? any clues?

**Comment by ralphbean** [comment]
@ryneeverett and @gdetrez were both working on bitbucket changes recently in #316 and #313.  Maybe they know?

FWIW, that [401 status code](https://http.cat/401) suggests that your credentials might just be incorrect (but it could also be a problem with the code...).

**Comment by gdetrez** [comment]
I agree with @ralphbean, it looks like your credentials are incorrect. You can try them with curl to check:
```
curl --user username:password https://api.bitbucket.org/1.0/user/repositories
```
If the same credentials work with curl but not bugwarrior then there might be a problem with the code.

**Comment by discipolo** [comment]
i fell into the oracle trap. once i figured out how to get bugwarrior-vault working again (had a rogue [hooks] section) i was able to get rid of the wrong credentials! thanks!

**Comment by ralphbean** [comment]
Glad to hear you worked it out!  :)
