### ISSUE TITLE
Please provide man pages

### ISSUE THREAD

**Issue by irl** [ralphbean/bugwarrior#330]
Debian considers a lack of man pages for applications as a bug.

W: bugwarrior: binary-without-manpage usr/bin/bugwarrior-pull
W: bugwarrior: binary-without-manpage usr/bin/bugwarrior-uda
W: bugwarrior: binary-without-manpage usr/bin/bugwarrior-vault

If you're not willing to write man pages, I'll take a go at writing them myself but I feel you'd be better qualified to do it.

**Comment by ryneeverett** [comment]
Perhaps this would be a good time to make these into actual subcommands rather than separate executables?

```
bugwarrior
    pull
    uda
    vault
```

Switching to subcommands seems like a usability improvement to me and then we'd only have to write one man page.

**Comment by ralphbean** [comment]
Would use of [help2man](https://www.gnu.org/software/help2man/) in the Debian build be sufficient?

**Comment by jwilk** [comment]
In my experience, `help2man` produces manpages that are ugly and insufficiently detailed.
In this particular case, such manpages would give very little clue how to use bugwarrior.
I'd prefer no manpages to `help2man`-generated ones.

**Comment by coddingtonbear** [comment]
We do have sphinx docs for bugwarrior, so I think we could just [ask sphinx to generate `manpage`s](http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.manpage.ManualPageBuilder) in addition to the normal HTML output, no?

**Comment by ralphbean** [comment]
It works when I run it, but the output manpage is not structured the way a typical manpage is.  It would help to add some top-level man pages with specific information about individual commands.
