### ISSUE TITLE
RFC: Make executables subcommands of a single bugwarrior executable.

### ISSUE THREAD

**Issue by ryneeverett** [ralphbean/bugwarrior#342]
```
bugwarrior
    pull
    uda
    vault
```

I would consider this primarily a usability improvement -- you only need to know one command and can `--help` yourself from there. Also avoids `bin` cluttering and is a more conventional cli design.

**Comment by DanielSchetritt** [comment]
What if you added something like this to your `.bashrc`?:
```bash
function bugwarrior {
        BUGWARRIOR_EXECUTABLES_DIR="/foo/bar"
        "$BUGWARRIOR_EXECUTABLES_DIR/bugwarrior-$*"
}
```

**Comment by ryneeverett** [comment]
My gripe is not with the user experience so much as:

1. Inconsistency with all other command line tools.
2. Pollution of my /BIN namespace.
3. Packaging inconvenience. Distributions systems tend to be streamlined for a single top-level executable.
4. You can't call `bugwarrior --help` to find out what the subcommands are.
