### ISSUE TITLE
Some services do not use asbool when importing config options that should

### ISSUE THREAD

**Issue by irl** [ralphbean/bugwarrior#347]
e.g.

https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/trac.py#L96

```
if self.config_get_default('no_xmlrpc', default=False):
```

This will return True if any value is defined for this option, including "False" and will only be false if the option is absent or set to the empty string. :/

We need a self.config_get_default_bool('option', default=False)

Something like:

```
def config_get_default_bool(option, default):
    return self.config_get_default(option, default).lower in ['true', 'yes', 'enabled']
```

**Comment by irl** [comment]
Ooops, we have this already.

So this is just an issue with the Trac service (perhaps also others).

**Comment by ryneeverett** [comment]
Personally I find the `asbool` acceptance of a bunch of alternative `True` values silly. If we're going to try to make the behavior consistent my vote would be to narrow it down to a single `True` value.

**Comment by irl** [comment]
Or go even futher, match it to ```True``` or ```False``` and fail config validation if it's not one of those.

**Comment by gdetrez** [comment]
I don't see the point of narrowing the accepted values at this point: it seems that it will just break backward compatibility without bringing any clear benefit, at lest none that I can see.

**Comment by irl** [comment]
Unless we had a transitional step where a few releases give warnings in the validation stage.

**Comment by ryneeverett** [comment]
> I don't see the point of narrowing the accepted values at this point: it seems that it will just break backward compatibility without bringing any clear benefit, at lest none that I can see.

This was my view until this bug report was opened and I still sympathize. But now that the silly feature requires maintenance I suspect eliminating it is less work than making it behave consistently and supporting it indefinitely.

**Comment by irl** [comment]
I think this is going off-topic a little, the point here is that the Trac service is currently broken, as if you have an entry of "trac.no_xmlrpc = False" in your service configuration, it will still not use xmlrpc.
