### ISSUE TITLE
Unicode in task description causes logging to throw exception

### ISSUE THREAD

**Issue by irl** [ralphbean/bugwarrior#350]
When a task contains non-ascii characters, logging will throw an exception and not display `INFO:bugwarrior.db:Updating task ...`.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
```

**Comment by ryneeverett** [comment]
1. It's odd that the first call is coming out of `logging` rather than bugwarrior. Are you sure that's the only error output?
2. Can you clarify "when a task contains"? In the title, in the description, in the url, in the comments, etc.
3. Was this with bugwarrior 1.4 or the development branch? If it's the development branch, could you check whether you have the same problem with 1.4?
4. Could you insert a non-ascii character in the appropriate place in this issue itself such that it would cause this error?

**Comment by irl** [comment]
```
{'priority': 'M', 'btsnumber': 145911, 'description': u'(bw)Is#145911 - bochs font is missing \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd umlau .. https://bugs.debian.org/145911', u'tags': [u'debian', u'foss'], 'btssource': u'bochs', 'project': u'debian.bochs', 'btsforwarded': u'bochs-developers@lists.sourceforge.net', 'btssubject': u'bochs font is missing \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd umlaute', 'btspackage': u'bochs', 'btsurl': 'https://bugs.debian.org/145911'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 38: ordinal not in range(128)
Logged from file db.py, line 363
```

I added a ```print "%r" % (issue,)``` to just before the logging.
https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/db.py#L361

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=145911 is the troublesome bug. There were others before but they appear to have been closed now and I didn't take note of them.

This could actually be a horrible mess complicated by the Debian BTS having mangled the Unicode, I'm not sure how well the BTS copes with it.
