### ISSUE TITLE
Bugzilla: 0 bugs found

### ISSUE THREAD

**Issue by nblock** [ralphbean/bugwarrior#355]
I'm trying to get bugwarrior 1.4 up and running against Bugzilla 5.0.3 using this configuration:

```
# Bugwarrior configuration

[general]
targets = bugzilla.company

[bugzilla.company]
service = bugzilla
bugzilla.base_uri = bugzilla-url
bugzilla.username = username
bugzilla.password = password
bugzilla.open_statuses = UNCONFIRMED,CONFIRMED,IN_PROGRESS
```

Running `bugwarrior-pull` prints the following

```
INFO:bugwarrior|Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
INFO:bugwarrior|Starting to aggregate remote issues.
INFO:bugwarrior|Spawning 1 workers.
INFO:bugzilla.company|Working on [bugzilla.company]
DEBUG:bugzilla.company| filtering on statuses: [u'UNCONFIRMED', u'CONFIRMED', u'IN_PROGRESS']
DEBUG:bugzilla.company| Found 0 total.
INFO:bugzilla.company|Done with [bugzilla.company] in 13.467277s
INFO:bugwarrior|Done aggregating remote issues.
INFO:db|Adding 0 tasks
INFO:db|Updating 0 tasks
INFO:db|Closing 0 tasks
```

The Bugzilla installation uses the following field values (Administration -> Field Values -> Status):
- UNCONFIRMED
- CONFIRMED
- IN_PROGRESS
- RESOLVED
- VERIFIED 

One interesting bit might be that this Bugzilla instance uses LDAP for authentication and the username on login differs from e.g. assigned fields. On login, I have to user `username` and once I'm logged in, Bugzilla identifies me with `someemail@company.com`.

**Comment by ralphbean** [comment]
Ah, interesting.  We'll probably need to differentiate between the login credentials and the identity used for filtering to make this work for you.

**Comment by nblock** [comment]
I modified the bugzilla installation such that login name now matches email.

**Comment by nblock** [comment]
I revisited bugwarrior and it works for me.

**Comment by ralphbean** [comment]
Thanks @nblock!
