### ISSUE TITLE
Support for youtrack

### ISSUE THREAD

**Issue by mozey** [ralphbean/bugwarrior#356]
Is there any plans to add support for jetbrains youtrack as a remote source?

**Comment by coddingtonbear** [comment]
There would be if you were planning to add such support, @mozey ;-); we really, really rely on people who actually use each supported service for writing the integration and helping out with testing during future releases.

They [do appear to have python bindings available](https://confluence.jetbrains.com/display/YTD6/Python+Client+Library), so adding a new service wouldn't be very difficult.  Check out [the services listed in the services directory](https://github.com/ralphbean/bugwarrior/tree/develop/bugwarrior/services) (the simplest of them is probably our [megaplan](https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/mplan.py) integration) to get an idea of what's required; it's not as complex as it might sound, and I'm sure I can speak for all of us when I say that we'd be glad to help if you bump into any questions!

**Comment by mozey** [comment]
@coddingtonbear I'll take a stab at it when I can squeeze in the time :)

I've setup the development environment (on OSX 10.10.5 with Python 2.7.11 virtualenv) as per the docs with some additional steps required:

tests_require in `setup.py` lists some of these not sure why `python setup.py develop` didn't take care of it?

    pip install nose
    pip install responses
    pip install jira
    pip install megaplan
    pip install pypandoc
    pip install pyac
    
Running the tests
    
    cd bugwarrior/tests 
    nosetests
    
    # Ran 39 tests in 2.080s
    # OK

**Comment by ryneeverett** [comment]
@mozey When you invoke `python setup.py nosetests` those dependencies are installed into a separate testing environment so you don't need to install them into your development environment. The way you did it is fine too.

**Comment by ryneeverett** [comment]
Resolved via #425.
