### ISSUE TITLE
Support for flagged emails in IMAP

### ISSUE THREAD

**Issue by irl** [ralphbean/bugwarrior#358]
Just an idea:
- Treat emails flagged in an IMAP folder as tasks
- Description is subject, can add body as annotation
- Considered "done" when the flag is removed
- URL is an `imap:` URL

Feedback would be good to develop this into something implementable. This concept is far too vague in my brain currently, but I think would be really useful, at least to me.

**Comment by ralphbean** [comment]
This is crazy.  Crazy good.  :)

I personally don't use imap flags, so I can't comment much further.

For what its worth, I do use ``mutt`` and I recall that [there was a tool for creating tasks out of incoming emails](https://www.nixternal.com/mark-e-mails-in-mutt-as-tasks-in-taskwarrior/).

**Comment by ralphbean** [comment]
Going to close this (cleaning up the queue). See also #410 for anyone who wants to contribute this as a patch.
