### ISSUE TITLE
bugwarrior should use data.location from ~/.taskrc instead of ~/.task

### ISSUE THREAD

**Issue by bowlofeggs** [ralphbean/bugwarrior#367]
Hello! My .taskrc has data.location defined to an OwnCloud share, so that I can easily share my tasks among devices. Thus, I do not have a ~/.task folder. When I run bugwarrior-pull, this is an issue:

```
 bugwarrior-pull 
/usr/lib/python2.7/site-packages/keyring/backends/Gnome.py:6: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
CRITICAL:command|oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/command.py", line 48, in pull
TRACE     lockfile.acquire(timeout=10)
TRACE   File "/usr/lib/python2.7/site-packages/lockfile/pidlockfile.py", line 94, in acquire
TRACE     raise LockFailed("failed to create %s" % self.path)
TRACE LockFailed: failed to create /home/rbarlow/.task/bugwarrior.lockfile
```

However, after I ```mkdir ~/.task```, all is well in the kingdom.

Thanks for making this awesome plugin!

**Comment by ryneeverett** [comment]
This issue will be resolved by #363 which gets the data location directly from taskwarrior which should be effectually the same as getting it from the .taskrc.

In the meantime you can set the environmental variable "TASKDATA" (which we're borrowing from [the taskwarrior configuration](https://taskwarrior.org/docs/configuration.html)) to override the default location.

**Comment by mathstuf** [comment]
#364 has been merged, this can be closed.

**Comment by ryneeverett** [comment]
Good call @mathstuf.
