### ISSUE TITLE
Embedded bugwarrior on android

### ISSUE THREAD

**Issue by albfan** [ralphbean/bugwarrior#368]
Would be possible to use:

https://github.com/kivy/python-for-android

to import x-to-taskwarrior for android?

I can test on my own fork: 

https://github.com/albfan/taskwarriorandroid

Before suggest patches so testing would be dependant on third party teams.

If there's other options (java implementation for bugwarrior or the like, please notice me)

**Comment by ryneeverett** [comment]
I wouldn't want to discourage you from this approach but I would think running bugwarrior on a server and syncing your android device from there could give you the same result a lot easier and also decrease the IO load on your android device.

**Comment by albfan** [comment]
Main idea is exactly to avoid that server in the middle. Let's see if it at least it run on android

**Comment by ralphbean** [comment]
Heh, yeah - I don't have interest in pursuing this.  This will involve some packaging work that I don't want to maintain.  Would be glad to know if someone gets it working, though!
