### ISSUE TITLE
[RFE] Better error messaging when users hit 404 while using a token to authenticate to GitHub

### ISSUE THREAD

**Issue by bowlofeggs** [ralphbean/bugwarrior#374]
Hello! I'm having some trouble connecting Bug Warrior to GitHub with token authentication. Here's my bugwarriorrc with the token redacted:

```
$ cat ~/.bugwarriorrc
[general]
targets: github_bowlofeggs

[bz]
service = bugzilla
bugzilla.base_uri = bugzilla.redhat.com
bugzilla.username = randy@electronsweatshop.com
bugzilla.password = REMOVED
description_template = {{bugzillabugid}} - {{bugzillasummary}} {{bugzillaurl}}

[github_bowlofeggs]
service = github
github.login = bowlofeggs
github.token = REMOVED
github.username = bowlofeggs
description_template = {{githubnumber}}: {{githubtitle}}

[notifications]
notifications = True
backend = gobject
finished_querying_sticky = False
task_crud_sticky = True
only_on_new_tasks = True
```

When using HEAD on the develop branch as of today, here is what happens when I bugwarrior-pull:

```


    [rbarlow@ohm bugwarrior]$ python
    Python 2.7.12 (default, Aug  9 2016, 15:48:18)
    [GCC 6.1.1 20160621 (Red Hat 6.1.1-3)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import bugwarrior
    /usr/lib/python2.7/site-packages/keyring/backends/Gnome.py:6: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
      from gi.repository import GnomeKeyring
    >>> bugwarrior.pull()
    INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
    INFO:bugwarrior.services:Starting to aggregate remote issues.
    INFO:bugwarrior.services:Spawning 1 workers.
    INFO:bugwarrior.services:Working on [github_bowlofeggs]
    ERROR:bugwarrior.services:Worker for [github_bowlofeggs] failed: Non-200 status code 404; u'https://api.github.com/user/issues?per_page=100'; u'{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}'
    Traceback (most recent call last):
      File "bugwarrior/services/__init__.py", line 515, in _aggregate_issues
        for issue in service.issues():
      File "bugwarrior/services/github.py", line 376, in issues
        issues.update(self.get_directly_assigned_issues())
      File "bugwarrior/services/github.py", line 298, in get_directly_assigned_issues
        for issue in self.client.get_directly_assigned_issues():
      File "bugwarrior/services/github.py", line 48, in get_directly_assigned_issues
        return self._getter(url)
      File "bugwarrior/services/github.py", line 73, in _getter
        json_res = self.json_response(response)
      File "bugwarrior/services/__init__.py", line 494, in json_response
        response.status_code, response.url, response.text,
    IOError: Non-200 status code 404; u'https://api.github.com/user/issues?per_page=100'; u'{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}'
    INFO:bugwarrior.services:Done with [github_bowlofeggs] in 9.010242s
    INFO:bugwarrior.services:Terminating workers
    CRITICAL:bugwarrior.command:Aborted (critical error in target 'github_bowlofeggs')
```

This is a wild guess, but I noticed when I tried out password auth that the URL it tried to use (and failed with, since my account is two-factor auth protected) had "bowlofeggs" in it and the URL listed in the above traceback does not. Could it be that bugwarrior uses the wrong URL when token auth is used?

**Comment by ryneeverett** [comment]
> This is a wild guess, but I noticed when I tried out password auth that the URL it tried to use (and failed with, since my account is two-factor auth protected) had "bowlofeggs" in it and the URL listed in the above traceback does not. Could it be that bugwarrior uses the wrong URL when token auth is used?

The url that returned the 404 is correct: https://developer.github.com/v3/issues/#list-issues.

See https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists.

**Comment by bowlofeggs** [comment]
Oh man, now I feel pretty silly, but to be honest 404 instead of 403 is also pretty silly. I went to look at that token in my auth settings, and I think it lacked the "public_repo" permission. If you create a token and don't check any of the boxes, it will say "public access" next to it. I had seen the bugwarrior docs that said "Only the public_repo scope is required" and for some reason I didn't notice the subtle (but important!) difference between "_repo" and " access".

Anyways, I'm happy to close this if you wish, or you might consider catching that 404 when token auth is being used, and maybe adding a message to make sure that both the token is right and that it's "public_repo" and not "public access". Choose your own adventure!

**Comment by ryneeverett** [comment]
> Oh man, now I feel pretty silly, but to be honest 404 instead of 403 is also pretty silly.

Agreed.

> you might consider catching that 404 when token auth is being used, and maybe adding a message to make sure that both the token is right and that it's "public_repo" and not "public access"

Seems reasonable to me.
