### ISSUE TITLE
Leverage pass storage

### ISSUE THREAD

**Issue by Fale** [ralphbean/bugwarrior#379]
Store plain text password in confg files is bad.
Many people already use pass.
I think it would be really nice to have an integration so that we can specify the pass object instead of the password in the config file

**Comment by irl** [comment]
@Fale you can already do this, but i think we need a documentation fix to explain how to do it

```
 irl@iain-desk$ cat .bugwarriorrc | grep pass
github.password = @oracle:eval:pass Web/GitHub/irl
trac.password = @oracle:eval:pass ERG/LDAP/iain
trac.password = @oracle:eval:pass Tor/Trac/irl
github.password = @oracle:eval:pass Web/GitHub/irl
```

**Comment by Fale** [comment]
Thanks irl, what's the '@oracle' bit?

**Comment by irl** [comment]
http://bugwarrior.readthedocs.io/en/latest/common_configuration.html#password-management

**Comment by Fale** [comment]
Thanks :)

**Comment by adriangalilea** [comment]
```
pip install bugwarrior[keyring]
zsh: no matches found: bugwarrior[keyring]
```
