### ISSUE TITLE
support for trello

### ISSUE THREAD

**Issue by carmackjia** [ralphbean/bugwarrior#38]
Trello is a collaboration tool that organizes projects into boards. In one glance, Trello tells you what's being worked on, who's working on what, and where something is in a process.  -- from trello.com

as trello provides a simple RESTful web API for a banch of its resource, add support for trello can be not too hard.

**Comment by coddingtonbear** [comment]
Oh, as an aside -- if you use bugwarrior via https://inthe.am/, you'd get trello integration for free.  Bugwarrior integration is, though, to be clear, a beta feature there.

**Comment by gdetrez** [comment]
@carmackjia I added support for trello in #319. If you want to give it a try, I'd love to hear your feedback :grinning:

**Comment by discipolo** [comment]
tested that branch a bit and it works great for me so far!
