### ISSUE TITLE
GnomeKeyring warning

### ISSUE THREAD

**Issue by Fale** [ralphbean/bugwarrior#380]
Executing `bugwarrior-pull` a gnome keyrin warning message appears

```
/usr/lib/python2.7/site-packages/keyring/backends/Gnome.py:6: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
```

**Comment by gdetrez** [comment]
I think this warning comes from the [keyring](https://github.com/jaraco/keyring) python library although it seems that the import in question is not there. You can try reporting the issue to your distro maybe...

**Comment by gdetrez** [comment]
Closing as it is not something we can fix.

**Comment by ryneeverett** [comment]
I agree that this doesn't seem to be actionable but I would note that clarifying our relationship with `keyring` is being tracked in #343.
