### ISSUE TITLE
Improved support for Redmine

### ISSUE THREAD

**Issue by kostajh** [ralphbean/bugwarrior#390]
Hi @ralphbean, as a heads up I'm working on a larger PR to improve the support available for Redmine (and a bunch of fields, support for annotations, etc). Let me know if you have any questions or concerns in the meantime!

**Comment by lzap** [comment]
Could you elaborate LIMIT/OFFSET? Currently only max of 25 records are found, this could be increased to 100 (maximum allowed) or ideally with pagination: http://www.redmine.org/projects/redmine/wiki/Rest_api

**Comment by lzap** [comment]
I created a simple patch to increase the limit to 100: https://github.com/ralphbean/bugwarrior/pull/394

Pagination would be super cool :-)

**Comment by ralphbean** [comment]
Seems like this was resolved by #395.
