### ISSUE TITLE
pulling from bugzilla fails due to email1?

### ISSUE THREAD

**Issue by albfan** [ralphbean/bugwarrior#412]
using this configuration in `~/.bugwarriorrc`

<pre>
[bugzilla_gnome]
service = bugzilla
bugzilla.base_uri = bugzilla.gnome.org
bugzilla.username = my@email.com
bugzilla.password = mypassword
</pre>

this is the error I get

<pre>
CRITICAL:bugzilla_gnome|Worker for [bugzilla_gnome] failed: <Fault 53: 'email1 is not a valid parameter for the Bugzilla::Bug::match function.'>
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 502, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/bz.py", line 216, in issues
TRACE     bugs = self.bz.query(query)
TRACE   File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1203, in query
TRACE     r = self._query(query)
TRACE   File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1194, in _query
TRACE     return self._proxy.Bug.search(query)
TRACE   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
TRACE     return self.__send(self.__name, args)
TRACE   File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 168, in _ServerProxy__request
TRACE     ret = ServerProxy._ServerProxy__request(self, methodname, params)
TRACE   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
TRACE     verbose=self.__verbose
TRACE   File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 259, in request
TRACE     return self._request_helper(url, request_body)
TRACE   File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 245, in _request_helper
TRACE     raise sys.exc_info()[1]
TRACE Fault: <Fault 53: 'email1 is not a valid parameter for the Bugzilla::Bug::match function.'>
INFO:bugzilla_gnome|Done with [bugzilla_gnome] in 2.921848s
</pre>

I try to add

    bugzilla.email = my@email.com
    bugzilla.email1 = my@email.com

but no luck

bugzilla on gnome is version 4.4.12

Any more config parameters that I should add?

**Comment by ralphbean** [comment]
As a first guess, try setting the undocumented bugzilla `advanced` option in your bugwarrior config file.  See this commit:  https://github.com/ralphbean/bugwarrior/commit/474e61eb8d2204855f6496b0bfa56f0e1aede3b4

**Comment by albfan** [comment]
I will try it as soon as possible. More info here:

https://bugzilla.redhat.com/show_bug.cgi?id=825370#c3
https://www.bugzilla.org/features/#searchpage

**Comment by towo** [comment]
Bump, just running into this myself. Setting `bugzilla.advanced = true` (or `yes`) doesn't seem to be helping.

**Comment by towo** [comment]
After dropping some debugging into `python-bugzilla` which I'm currently working on anyway:

```
DEBUG:bugzilla.base:Bugzilla version string: 4.4.9
[...]
DEBUG:bugzilla.base:Calling Bug.search with: {'column_list': ['id', 'status', 'summary', 'priority', 'product', 'component', 'flags', 'longdescs'], 'bug_status': ['NEW', 'ASSIGNED', 'NEEDINFO', 'ON_DEV', 'MODIFIED', 'POST', 'REOPENED', 'ON_QA', 'FAILS_QA', 'PASSES_QA'], 'email1': 'some.email@here', 'emailreporter1': 1, 'emailassigned_to1': 1, 'emailqa_contact1': 1, 'emailtype1': 'substring', 'emailcc1': 1, 'query_format': 'advanced'}
ERROR:bugwarrior.services:Worker for [some.host.here] failed: <Fault 53: 'email1 is not a valid parameter for the Bugzilla::Bug::match function.'>
```

So it appears the `query_format` isn't the only issue at play here, at least no primarily. (I've seen some code to remove query_format if it's the *only* parameter, maybe that triggers for some reason)

**Comment by towo** [comment]
From what I'm currently sort of finding out, it may be that actually running any significant queries of the XMLRPC API may just be a bugzilla.redhat.com thing. Which would kind of suck.

**Comment by ryneeverett** [comment]
Triage: I'd imagine that this is resolved or at least a different situation since #707 (and the upstream changes in python-bugzilla linked therein).
