### ISSUE TITLE
Pulling from redmine to the correct project

### ISSUE THREAD

**Issue by johanv** [ralphbean/bugwarrior#413]
Thank you for creating this great project, I am now happily pulling redmine items to my taskwarrior.

Now I have a feature request :-)

In our redmine instance, I am working on multiple projects. It would be nice if bugwarrior-pull 2ould automatically figure out the project of a redmine issue, and add the task to the corresponding taskwarrior project, instead of adding all the redmine issues to the same project as it is doing right now.

**Comment by ralphbean** [comment]
Most of our other service backends work this way, it must just be something weird about our redmine plugin.  Hm...

**Comment by ralphbean** [comment]
@johanv, can you paste here a sanitized version of the redmine section of you bugwarrior config file?  (remove passwords!)

**Comment by johanv** [comment]
Thank you @ralphbean foor looking into this. As it seems, I had just misconfigured the redmine section, sorry for that. I based my configuration on the [example in the documentation](https://bugwarrior.readthedocs.io/en/latest/services/redmine.html), but after leaving out the line

    redmine.project_name = redmine

everything works as expected. So I will close the issue.

**Comment by ralphbean** [comment]
Good, good.  :)  Cheers!
