### ISSUE TITLE
CalDAV support?

### ISSUE THREAD

**Issue by towo** [ralphbean/bugwarrior#418]
So, CalDAV supports task lists. Is any support planned, already integrated and I overlooked it, or do I need to get busy with it?

**Comment by gdetrez** [comment]
I haven't heard of anything in this regard, feel free to get busy with it :wink:

**Comment by ralphbean** [comment]
Yeah, this one's all you @towo!  :)

**Comment by towo** [comment]
Okay, keep this open, I'll dump something in here eventually.

**Comment by jspricke** [comment]
You could use this as a start: https://github.com/jspricke/python-icstask

**Comment by ryneeverett** [comment]
Going to close this (cleaning up the queue). However, do see #410 for anyone who wants to contribute this as a patch.
