### ISSUE TITLE
Trouble with GitHub only_if_assigned

### ISSUE THREAD

**Issue by kostajh** [ralphbean/bugwarrior#420]
I'm finding that Bugwarrior is pulling issues that are not assigned to me. Maybe I am doing something wrong with my config?

For example, Bugwarrior is pulling `https://github.com/savaslabs/autism-case-study/pull/68` even though I am not assigned there.

There relevant section of my config is:

```
[github_savas]
service = github
default_priority = M
add_tags = work
github.login = kostajh
github.username = savaslabs
github.only_if_assigned = kostajh
github.also_unassigned = False
```

**Comment by gdetrez** [comment]
I didn't manage to reproduce this issue. With the given config I only got a bunch of PR but bugwarrior didn't pull the issue you mentioned.

What version of bugwarrior are you using? If you got it from a release, maybe try the version in `develop` to see if the problem has already been fixed.

**Comment by kostajh** [comment]
I'm using the `develop` version of Bugwarrior via [these docs](https://bugwarrior.readthedocs.io/en/latest/contributing.html#setting-up-your-development-environment). Hmm.

**Comment by gdetrez** [comment]
Oh, wait. I think I missed the fact that https://github.com/savaslabs/autism-case-study/pull/68 is a pull request. Try adding `github.filter_pull_requests = True` in your config.

**Comment by kostajh** [comment]
I'll try that, but I do want pull requests in my task list -- just the
ones assigned to me, though.




On Wed, Dec 7, 2016, at 05:24 AM, Grégoire Détrez wrote:

> Oh, wait. I think I missed the fact that savaslabs/autism-case-
> study#68[1] is a pull request. Try adding github.filter_pull_requests
> = True in your config.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/savaslabs/autism-case-study/pull/68
  2. https://github.com/ralphbean/bugwarrior/issues/420#issuecomment-265410906

**Comment by gdetrez** [comment]
> I do want pull requests in my task list -- just the ones assigned to me

That's what `github.filter_pull_requests` should do in this case.

**Comment by kostajh** [comment]
That seems to have worked. Thanks!
