### ISSUE TITLE
Support GitHub reviewer functionality

### ISSUE THREAD

**Issue by kostajh** [ralphbean/bugwarrior#423]
Currently, a pull request will show up in one's task list if `filter_pull_requests = True` is set and that user is marked as "Assigned". But if you are marked as "Reviewer", and not "Assigned", the pull request won't show up in the task list. Docs on [Review Requests](https://developer.github.com/v3/pulls/review_requests/).

**Comment by djmitche** [comment]
I've been thinking of adding support for arbitrary queries.  For example, [is:open review-requested:djmitche](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+review-requested%3Adjmitche) is exactly the set of tasks I'd like to sync, but in your case you might want to do some additional filtering or tweaking of the query.
