### ISSUE TITLE
bugwarrior conflicts with version of future in fedora

### ISSUE THREAD

**Issue by mikem23** [ralphbean/bugwarrior#427]
I removed "future!=0.16.0" from setup.py and it seems to be working fine for me after that. This is on F24.

**Comment by ralphbean** [comment]
Hm.. that's odd.  There is some discussion in #406 on the problems with that specific release of `future`.  Perhaps they were fixed by the Fedora packager?

**Comment by mikem23** [comment]
well, I am running it under python2, so perhaps that is the difference. There is no python3-jira in f24 it seems.

**Comment by mikem23** [comment]
though, if I disable the jira config and run it with py3 it also seems to be ok.
Fedora updated to 0.16.0 on 13 Dec 2016, and it looks like they only have one patch on top of that

    Patch0: %{name}-skip_tests_with_connection_errors.patch

**Comment by ssbarnea** [comment]
Can we please fix this? Banning current version of future just because it was messed by the Fedora repackaging creates problems for all other users.

If is broken on Fedora, add a requirement marker for Fedora only but not for all users.
