### ISSUE TITLE
Quotes in issue summary get escaped

### ISSUE THREAD

**Issue by lubomir** [ralphbean/bugwarrior#429]
I have imported issues from Jira. One of the issues has a summary with double quotes. Taskwarrior is now showing it as `&dquot;`.

```
$ task 10 info | grep Description
Description    (bw)Is#1282 - dist-git-utils: some &dquot;non-manual wa ..
```

Adding a task manually via `task add …` with such character works correctly.

Getting the task from Jira does not escape it either

```
In [26]: j = jira.client.JIRA(…)

In [27]: j.issue('COMPOSE-1282').fields.summary
Out[27]: u'dist-git-utils: some "non-manual way" how to display current dist-git policy.'
```

Any idea where this escaping is coming from?

**Comment by ralphbean** [comment]
I bet it is coming from here:  https://github.com/ralphbean/taskw/blob/develop/taskw/utils.py#L23-L54

**Comment by ryneeverett** [comment]
triage: anybody still experiencing this?
