### ISSUE TITLE
Document description_length

### ISSUE THREAD

**Issue by nyov** [ralphbean/bugwarrior#432]
The `description_length` field (https://github.com/ralphbean/bugwarrior/pull/76) has vanished from the README and documentation.
It just took me half an hour to figure out why bw cut off task descriptions and how to change that.
Please include it again in the docs? A saner default would also be appreciated (say 72 or 79 chars, not 35).

**Comment by ralphbean** [comment]
Ah, the `description_length` field got documented in d8a82d2b83cc3ebe10c224c66d662cd400c20dc9 and is available [here](http://bugwarrior.readthedocs.io/en/latest/common_configuration.html#common-service-configuration-options).
