### ISSUE TITLE
Support for unbounded length annotations?

### ISSUE THREAD

**Issue by pjf** [ralphbean/bugwarrior#441]
I am *loving* bugwarrior, not least because rather than having to visit 3rd-party tools I can see everything I'm doing right in TaskWarrior. It's seriously made an enormous impact to both my workflow and my enjoyment of getting things done in general. However, I'm having a tricky time finding a clean way to allow unbounded length annotations.

I was hoping that setting `annotation_length = 0` would allow annotations to be of any length; instead it appears to reduce annotations to the shortest length possible, which is the opposite of what I'm after.

Right now I've got `annotation_length` set to a very large number, but that doesn't feel like a very clean way of doing things.

Is there a way to tell bugwarrior to use unbounded length annotations, or if not, may I humbly suggest `annotation_length = 0` be a way of doing this?

**Comment by ryneeverett** [comment]
See PR's #436, #437, and #438. There wasn't a canonical issue for this feature, so now this is it.
