### ISSUE TITLE
[vague proposal] new structure allowing more arbitrary queries

### ISSUE THREAD

**Issue by djmitche** [ralphbean/bugwarrior#446]
I find most of the "canned" queries in bugwarrior inadequate.  I don't necessarily want everything assigned to me, but maybe I do want a few things that aren't assigned to me.  Some I want to give different tags.  And so on.

For some purposes, I've managed to get this to work, but one of the major issues I've run into is that taskwarrior and/or bugzilla get very confused if two different sections produce tasks with the same identifiers.  For example, if I have a bugzilla section for bugs assigned to me, and a bugzilla section for bugs requiring my review, then once someone requests a review on a bug assigned to me, my taskwarrior DB gets corrupted.

I also have the problem that I would like to use a few specific search strings with the github service, each treated differently, rather than try to express my needs as a long list of github-related sections in the config file.  But the github service does not allow arbitrary filters.

So the vague proposal is this:
 * Refactor configuration to always allow raw queries, and document how to generate them (so, no automatic filtering, no built-in notion of "my" issues, etc.)
 * Refactor so operation proceeds as follows:
   * For all services, enumerate all matching issues
   * Apply any service-specific transforms (adding tags, custom description)
   * Generate a unique, stable identifier for each (in most cases, the canonical issue URL).  This identifier should be stable across multiple queries, so if the same bug is matched twice, it maps to a single identifier
    * Where the same key appears twice, apply some simple heruistic to select a "winner" (such as the union of the tags and the longest description)
    * Compare the resulting list against the list of bugwarrior-managed tasks in taskwarrior, adding tasks, updating descriptions, adding tags, or completing tasks as necessary

I realize both of these would be breaking changes and that's not great.  Still, I'm interested to hear feedback on the idea.

**Comment by ryneeverett** [comment]
It seems like there are a few different issues that could be addressed separately:

- Unique issue identifiers to avoid duplicates and corruption.
- Allow arbitrary task selection queries.
- Add hook for arbitrary task transforms.

The remainder of your proposal relating to duplicate identifiers I'm having trouble understanding. Why do we need to select "winners" if we have unique identifiers? Why would the same key appear twice if our identifiers are unique? I must be missing something.

**Comment by djmitche** [comment]
Two filters on the same service might identify the same issue. For example,
a bug matching the "assigned" filter, and also matching the filter for
review requests.

**Comment by ryneeverett** [comment]
@djmitche Ok, but why would it matter which issue is picked as the "winner" if they are truly identical? Why would they have different tags/description?

**Comment by djmitche** [comment]
Yeah, sorry, I should have waited to answer until I could provide more details.  Right now, I have this setup:

```
[bugzilla_mozilla]
service = bugzilla
bugzilla.base_uri = bugzilla.mozilla.org
bugzilla.ignore_cc = True
# assigned
bugzilla.query_url = https://bugzilla.mozilla.org/query.cgi?list_id=13320987&resolution=---&emailtype1=exact&query_format=advanced&emailassigned_to1=1&email1=dustin%40mozilla.com&product=Taskcluster
add_tags = bugzilla
project_template = moz 
description_template = http://bugzil.la/{{bugzillabugid}} {{bugzillasummary}}

[bugzilla_mozilla_respond]
service = bugzilla
bugzilla.base_uri = bugzilla.mozilla.org
bugzilla.ignore_cc = True
# ni?, f?, r?, not assigned
bugzilla.query_url = https://bugzilla.mozilla.org/query.cgi?j_top=OR&list_id=13320900&emailtype1=notequals&emailassigned_to1=1&o4=equals&email1=dustin%40mozilla.com&v4=dustin%40mozilla.com&o7=equals&v6=review%3F&f8=flagtypes.name&j5=OR&o6=equals&v7=needinfo%3F&f4=requestees.login_name&query_format=advanced&f3=OP&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&f5=OP&v8=feedback%3F&f6=flagtypes.name&f7=flagtypes.name&o8=equals
add_tags = bugzilla, respond
project_template = moz 
description_template = http://bugzil.la/{{bugzillabugid}} {{bugzillasummary}}
```

So, two different queries of the same bugzilla instance, applying different tags in this case.  You'll see that the second explicitly excludes assigned.  Without that exclusion, when a bug is both assigned to me and flagged for review, bugwarrior gets confused, I think because it adds the bug twice, and then finds two matching tasks on its next run.  I would like for bugwarrior to recognize that they are the same bug and take the union of the tags (in this case, bugzilla, respond), and create/update a single task.

**Comment by ryneeverett** [comment]
>  You'll see that the second explicitly excludes assigned. Without that exclusion, when a bug is both assigned to me and flagged for review, bugwarrior gets confused, I think because it adds the bug twice, and then finds two matching tasks on its next run. I would like for bugwarrior to recognize that they are the same bug and take the union of the tags (in this case, bugzilla, respond), and create/update a single task.

- I agree that the behaviour you're describing is a bug, though I don't understand how it's happening unless the remote bugzilla instance is reporting different `id`'s for the same issue. Perhaps this is a bug in bugzilla or perhaps there is a more appropriate field we could use as a UUID.
- Union of tags *should* be the current merge behavior.
- I'm pretty sure the description priority is based on chronology and I agree that a more controllable heuristic would be better. (Maybe first in configuration file?)

So here's the issues from my updated perspective:

- Bug: Bugzilla `id`'s for the same issue are different when retrieving with different API queries.
- Bug: Store union of remote tags.
- Feature: Simple heuristic for description template priority.
- Feature: Arbitrary task selection queries.
- Feature: Hook for arbitrary task transforms.

**Comment by djmitche** [comment]
Thanks for the pointer to #447.  I added #449 for the second bug (union of remote tags) and mentioned the first feature.

I think the latter two can be left for now -- perhaps it's just a personal preference of mine, and in any case the services I care about largely support it now.  So, I think this vague issue is now made specific in the other bugs and can be closed.
