### ISSUE TITLE
Feature Request: Trello due-date support

### ISSUE THREAD

**Issue by pjf** [ralphbean/bugwarrior#457]
Trello currently allows a due date to be set on cards, but as far as I can tell, we don't import this date at all.

It would be lovely if we could import this directly into taskwarrior, or at the very least supply it as a UDA.

~ Paul

**Comment by swalladge** [comment]
[ogarcia/trellowarrior](https://github.com/ogarcia/trellowarrior) supports syncing dates, albeit with [issues](https://github.com/ogarcia/trellowarrior/issues/7). Perhaps worth a look if implementing in bugwarrior.

**Comment by mattcen** [comment]
This is fixed by #629 and can be closed.
