### ISSUE TITLE
"Error formatting message" with bugwarrior-pull and gitlab

### ISSUE THREAD

**Issue by duanearnett** [ralphbean/bugwarrior#461]
Getting the error below when trying to `bugwarrior-pull`.  

`{u'message': u'401 Unauthorized'}"` Looks suspect/malformed to me. I installed using pip and everything has been working fine until a few weeks ago. I'm not too familiar with pip but is there an upgrade method for this package or should I install from source to be able to keep up with updates?

**Full output:**
````
INFO:bugwarrior|Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
INFO:bugwarrior|Starting to aggregate remote issues.
INFO:bugwarrior|Spawning 1 workers.
INFO:gitlab|Working on [gitlab]
2017-03-29T13:50:02Z:INFO:twiggy.internal|Error formatting message level: <LogLevel CRITICAL>, format: u"Worker for [gitlab] failed: Non-200 status code 401; 'https://gitlab.com/api/v3/projects'; {u'message': u'401 Unauthorized'}", fields: {'name': u'gitlab', 'time': <built-in function gmtime>}, options: {'suppress_newlines': True, 'style': 'braces', 'trace': 'error'}, args: (), kwargs: {}
TRACE Traceback (most recent call last):
TRACE   File "/usr/local/lib/python2.7/site-packages/twiggy/logger.py", line 246, in _emit
TRACE     msg = Message(level, format_spec, self._fields.copy(), self._options.copy(), args, kwargs)
TRACE   File "/usr/local/lib/python2.7/site-packages/twiggy/message.py", line 86, in __init__
TRACE     s = format_spec.format(*args, **kwargs)
TRACE KeyError: u"u'message'"
INFO:gitlab|Done with [gitlab] in 1.845147s
INFO:bugwarrior|Terminating workers
CRITICAL:command|Aborted (critical error in target 'gitlab')
````

Thanks for your help. Please let me know if I can provide any other information/versions to help debug.

**Comment by ryneeverett** [comment]
The exception was raised in twiggy, which was removed since the last release. Therefore I don't think this is an actionable issue.

Usually you'll want to pip install from pypi but a workaround for your problem is to install the development version: `pip install -U git+https://github.com/ralphbean/bugwarrior.git@develop#egg=bugwarrior`.

**Comment by duanearnett** [comment]
That worked @ryneeverett, thanks for your help!
