### ISSUE TITLE
gerrithub support is broken: No JSON object could be decoded

### ISSUE THREAD

**Issue by ssbarnea** [ralphbean/bugwarrior#463]
I tried to configure gerrithub using a configuration like below and got an error:
```
[gerrithub]
service = gerrit
gerrit.base_uri = https://review.gerrithub.io/
gerrit.username = xxx
gerrit.password = token-obtained-from-profile
```
Error:
```
ERROR:bugwarrior.services:Worker for [gerrithub] failed: No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/ssbarnea/os/bugwarrior/bugwarrior/services/__init__.py", line 506, in _aggregate_issues
    for issue in service.issues():
  File "/Users/ssbarnea/os/bugwarrior/bugwarrior/services/gerrit.py", line 115, in issues
    changes = json.loads(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Also it worth mentioning the fact that gerrit support is not even available on the last release. To add to the confusion this is included in the current documentation.

Also if you do not mind, I think it would work updating the version from https://github.com/ralphbean/bugwarrior/blob/develop/setup.py#L3 because currently it states 1.4 which was already released. I had a good experience migrating to use of [pbr](https://docs.openstack.org/developer/pbr/) that saved me from the churns of updating versions inside the source code.

**Comment by ryneeverett** [comment]
> Also it worth mentioning the fact that gerrit support is not even available on the last release. To add to the confusion this is included in the current documentation.

Yes, that is indeed unfortunate. However, short of maintaining separate docs for every release, the practical solution is to release often enough that the latest release doesn't lag too far behind the docs. I believe all of the maintainers wish we released more often.

> Also if you do not mind, I think it would work updating the version from https://github.com/ralphbean/bugwarrior/blob/develop/setup.py#L3 because currently it states 1.4 which was already released. I had a good experience migrating to use of pbr that saved me from the churns of updating versions inside the source code.

I've had a good experience with [setuptools-scm](https://github.com/pypa/setuptools_scm) myself. However, updating the source code hasn't been a burden given how infrequently we release. Are there any practical consequences of leaving the latest release version in the source code?
