### ISSUE TITLE
Templates are loaded with service_prefix

### ISSUE THREAD

**Issue by nblock** [ralphbean/bugwarrior#466]
In the current devel branch (21f46eabf0cb53f21f3982424f39a78c4475d251) field templates are loaded with service_prefix: https://github.com/ralphbean/bugwarrior/blame/develop/bugwarrior/config.py#L287 

According to https://bugwarrior.readthedocs.io/en/latest/common_configuration.html#field-templates field templates should be specified as 'FIELD_template' without a service prefix being used. As the field is not found, its default None is used which leads to ```TypeError: Can't compile non template nodes``` when Jinja tries to render the template.

**Comment by ryneeverett** [comment]
I believe this is a documentation bug (though it was probably true when written). We've been moving toward consistently using the service prefix.

**Comment by nblock** [comment]
OK, I'll take a look at it next week.

**Comment by ryneeverett** [comment]
Resolved via #469. Thanks!
