### ISSUE TITLE
Fossil integration

### ISSUE THREAD

**Issue by Gasman2014** [ralphbean/bugwarrior#471]
I believe that there was a working Fossil import module for Bugwarrior and at some point I had a functioning setup. Due to a system update I now have lost this and can't find what happened to it. It does not seem to be in the current bugwarrior tree. There is a rather confusing message at Issue #87 

What is the situation regarding this module?

**Comment by ryneeverett** [comment]
You must have been using @umonkey's module which has never been included in the official bugwarrior package. @mathstuf's critique of the module is still applicable and it would likely need further tweaking to meet the current bugwarrior service specification.

Closing as #87 is the canonical issue for tracking this feature. Feel free to cherry-pick the module from @FvD's repository, bring it up to date, and submit a pull request.

**Comment by Gasman2014** [comment]
Thank you. I will give it a go!
