### ISSUE TITLE
Show also tasks from Taiga, not only userstories

### ISSUE THREAD

**Issue by fmauch** [ralphbean/bugwarrior#473]
Today I tried bugwarrior for Taiga and I was a little bit disappointed that it only showed one task, though I had more in my Taiga's dashboard. I figured out, there was only one userstory and multiple tasks (some of them were from other userstories though).

After a look into the source code, I got a q&d task import mechanism as well. 

Is there an intention behind only going for userstories or would a PR also querying tasks be considered?

Cheers, Felix

**Comment by ryneeverett** [comment]
Resolved via #499.
