### ISSUE TITLE
JIRA 403 using Kerberos authentication

### ISSUE THREAD

**Issue by jdcasey** [ralphbean/bugwarrior#475]
I'm seeing a strange issue here. I use Kerberos authentication to access the JIRA instance, but if this is the only authentication I've performed I get nothing but 403 status responses from JIRA. To work around this, I kill my krb ticket, then logout / login to JIRA using normal username / password access, telling it to remember me (establishing the cookie, I guess?). After that it works for some time, then stops again and I have to repeat this process.

It looks like kerberos access doesn't establish a cookie, probably because the ticket lifespan takes the place of the cookie's expiration. I didn't realize cookies were stored centrally in linux...it's interesting that it can access the Firefox cookie store, which it must do, since using the browser to login fixes bugwarrior.

I think it might be related to:

https://github.com/ralphbean/bugwarrior/issues/212

**Comment by ryneeverett** [comment]
triage: Is this still an issue? Even if it is it doesn't seem like there would be anything we could do about it.
