### ISSUE TITLE
1.5.0 release?

### ISSUE THREAD

**Issue by djmitche** [ralphbean/bugwarrior#478]
There's been a lot since mid-march:
  https://github.com/ralphbean/bugwarrior/compare/1.4.0...develop
I'm partial to my API-key fix of course, but maybe it's time for 1.5.0?

**Comment by ralphbean** [comment]
On it.

**Comment by ralphbean** [comment]
https://pypi.python.org/pypi/bugwarrior/1.5.1

**Comment by djmitche** [comment]
Thanks!!
