### ISSUE TITLE
Make an issue reappear after deletion

### ISSUE THREAD

**Issue by Plup-io** [ralphbean/bugwarrior#480]
Hi guys, 

I'm looking for a way to recover after a misuse of bugwarrior with gitlab.com. I had trouble with the gilab connection so I removed it from the configuration in order to make things work with the others repositories. Then I solved the issue and restore my configuration but my ticket from gitlab.com are gone. 

Is there a way to make them appaear again ?

**Comment by ryneeverett** [comment]
Removing a service from your configuration should not cause tasks that have already been added from that service to disappear from your taskwarrior database.

**Comment by Plup-io** [comment]
My bad. Indeed they are here. I just lost myself in my tasks. Sorry.
