### ISSUE TITLE
Import GitHub milestones as tasks

### ISSUE THREAD

**Issue by paralin** [ralphbean/bugwarrior#485]
If we're using GitHub as a issue tracking system, it makes sense to treat milestones like epics.

Any issues assigned to the milestone would appear as sub-tasks (linked) to the milestone. This way, when working on work for a milestone, and not a specific issue, there's a corresponding issue.

**Comment by ryneeverett** [comment]
For example, if the milestone is cutting a release of software there might be certain tasks associated with the milestone that don't belong in specific issues (changing version numbers, updating changelogs, building/pushing packages to repositories, etc.). Is this the kind of use case you have in mind?

**Comment by paralin** [comment]
No....

Have one issue that represents the milestone and link the issues assigned to that milestone to it as sub-issues blocking resolution of the milestone. Then Taskwarrior will represent the issue heirarchy correctly.

**Comment by paralin** [comment]
The same kind of goes for Jira tasks that have blockers, not sure if you read that or not as of now

**Comment by ryneeverett** [comment]
> Then Taskwarrior will represent the issue heirarchy correctly.

Can you be more specific about the representation you're after? It isn't clear to me what new view of the tasks this feature enables.

**Comment by paralin** [comment]
Yes, Taskwarrior can handle dependencies between tasks, what is blocking what, etc. It shows it in the task command line output, uses it to figure out what you should do next and adjust urgency, and it's rendered heirarchically in taskwiki and other viewers.

**Comment by ryneeverett** [comment]
Is the problem this solves that dependencies of milestone tasks cannot be easily viewed as part of the milestone?

**Comment by paralin** [comment]
Rephrasing slightly; the issues that are part of a milestone are not represented as such. There is a one to many relationship between milestone and issue. Issues block the milestone. 

This way you can also set a due date on a milestone and have the sub issues prioritized as such.

**Comment by ryneeverett** [comment]
Gotcha. I'd be supportive of adding this as an optional feature.

**Comment by ryneeverett** [comment]
triage: This is looking stale as no one has been interested in in implementing it.

**Comment by paralin** [comment]
No problem!
