### ISSUE TITLE
Google Tasks Support

### ISSUE THREAD

**Issue by ryneeverett** [ralphbean/bugwarrior#487]
The following is copied from [a comment](https://github.com/ralphbean/bugwarrior/issues/442#issuecomment-282004477) by @emmajane:

> Hello! I am reading this and I use Gmail for task management! I specifically use their keyboard shortcut to send an email to their "tasks".
>
> My workflow currently looks like this:
>
> - Triage Gmail inbox using [ and ] shortcuts (send to archive; move to next message in the inbox).
> - If there is an email that requires follow-up, I first send the message to Gmail tasks using shift+t.
>
> This action adds the task to a pop-up window which appears in the bottom right of my screen (see attached).
>
> ![attached](https://cloud.githubusercontent.com/assets/1299320/23262675/6e49967e-f9d3-11e6-8dce-32a34d665188.png)
>
> This also appears as a stand-alone screen at: https://mail.google.com/tasks/canvas?pli=1
>
> There are Gmail help pages at: https://support.google.com/mail/answer/106237?hl=en I believe this is the relevant API documentation: https://developers.google.com/google-apps/tasks/
>
> I'm happy to provide more details if they would be useful.

**Comment by StephanMeijer** [comment]
Is google task now supported?

**Comment by ryneeverett** [comment]
No, it was never implemented.

**Comment by StephanMeijer** [comment]
I'll probably take a look into implementing this.

**Comment by ryneeverett** [comment]
Going to close this (cleaning up the queue). However, do see #410 for anyone who wants to contribute this as a patch.
