### ISSUE TITLE
'gmail' in [my_gmail] is not a valid service

### ISSUE THREAD

**Issue by jeremiah** [ralphbean/bugwarrior#492]
Hi,

I'm trying to authenticate to Gmail and have gone through the steps (I believe) but am having trouble with my config that I cannot seem to fix. For some reason bugwarrior-pull, with or without --dry-run, fails to see my configuration of Gmail as a valid service;

```
CRITICAL:bugwarrior.config:
*************************************************
* There was a problem with your bugwarriorrc    *
*   'gmail' in [my_gmail] is not a valid service.
* Here's an example template to help:           *
*************************************************
```

**Comment by ryneeverett** [comment]
Can you share a bugwarriorrc file that reproduces this error?

**Comment by jeremiah** [comment]
[general]

# Here you define a comma separated list of targets.  Each of them must have a
# section below determining their properties, how to query them, etc.  The name
# is just a symbol, and doesn't have any functional importance.
targets = my_gmail

# Setting this to true will shorten links with http://da.gd/
shorten = True

# If unspecified, the default taskwarrior config will be used.
#taskrc = /path/to/.taskrc

# Setting this to True will include a link to the ticket in the description
inline_links = False

# Setting this to True will include a link to the ticket as an annotation
annotation_links = True

# Setting this to True will include issue comments and author name in task
# annotations
annotation_comments = True

# Defines whether or not issues should be matched based upon their description.
# In legacy mode, we will attempt to match issues to bugs based upon the
# presence of the '(bw)' marker in the task description.
# If this is false, we will only select issues having the appropriate UDA
# fields defined (which is smarter, better, newer, etc..)
legacy_matching = False

# log.level specifies the verbosity.  The default is DEBUG.
# log.level can be one of DEBUG, INFO, WARNING, ERROR, CRITICAL, DISABLED
log.level = DEBUG

# If log.file is specified, output will be redirected there.  If it remains
# unspecified, output is sent to sys.stderr
# log.file = bugwarrior.log

# Configure the default description or annotation length.
#annotation_length = 45

# Use hooks to run commands prior to importing from bugwarrior-pull.
# bugwarrior-pull will run the commands in the order that they are specified
# below.
#
# pre_import: The pre_import hook is invoked after all issues have been pulled
# from remote sources, but before they are synced to the TW db. If your
# pre_import script has a non-zero exit code, the `bugwarrior-pull` command will
# exit early.
#[hooks]
# pre_import = /home/someuser/backup.sh, /home/someuser/sometask.sh

# This section is for configuring notifications when bugwarrior-pull runs,
# and when issues are created, updated, or deleted by bugwarrior-pull.
# Three backends are currently supported:
#
#  - growlnotify (v2)   Mac OS X   "gntp" must be installed
#  - gobject            Linux      python gobject must be installed
#
# To configure, adjust the settings below.  Note that neither of the #
# "sticky" options have any effect on Linux.  They only work for
# growlnotify.
#[notifications]
# notifications = True
# backend = growlnotify
# finished_querying_sticky = False
# task_crud_sticky = True
# only_on_new_tasks = True

[my_gmail]
service = gmail

gmail.query = label:action OR label:readme
gmail.login_name = jeremiah.foster@gmail.com

**Comment by ryneeverett** [comment]
Are you using the latest `develop` branch version of bugwarrior from github?

**Comment by jeremiah** [comment]
Nope. I downloaded 8074e61.

Should I use the 'develop' branch?

**Comment by ryneeverett** [comment]
Yes, you should use the develop branch. Sorry for the confusion.

The docs are built off of the develop branch so they often include features that haven't made it into master or the latest release. This is because nobody has proposed or implemented a better solution.

**Comment by michaelgold** [comment]
I'm getting the same issue (even after compiling the latest development version). Is the gmail service code in the latest development branch?

**Comment by ryneeverett** [comment]
@michaelgold Yes, the gmail service is in the latest `develop` branch: https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/gmail.py
