### ISSUE TITLE
Reviews (Differential) support for Phabricator

### ISSUE THREAD

**Issue by swills** [ralphbean/bugwarrior#500]
For the Phabricator service support, it would be nice to support putting in items from Differential (code reviews) as well as the existing Maniphest (bugs) support. I have a number of code reviews that I need to look at and having those show up in Taskwarrior via Bugwarrior would be really helpful.

**Comment by urzds** [comment]
This actually works already:
```
[...]
INFO:bugwarrior.services.phab:Found 10 differentials                                                                             
[...]
```

The description of these tasks is set to `(bw)PR#D…`.

**Comment by urzds** [comment]
I propose to close this issue.

**Comment by ryneeverett** [comment]
Further evidence that this is already supported just came in #576.
