### ISSUE TITLE
[service/gitlab] tasks are completed and re-added when labels/tags change

### ISSUE THREAD

**Issue by wookietreiber** [ralphbean/bugwarrior#506]
I discovered that task are marked as complete and re-added when tags change. You can see this here with the three **backlog** to **backlog lhf** tasks (the green ones):

![bugwarrior-complete-and-add-again](https://user-images.githubusercontent.com/827088/28779559-e257897a-7603-11e7-917b-6b4448399edf.png)

My expectation was, that the original tasks would be modified in place. Is that possible with configuration or does this require a patch? I'd be willing to provide a PR if needed, but I wanted to ask about this first.

**Comment by ryneeverett** [comment]
triage: It's not clear how tag changes could cause this but it does seem similar to #552.

**Comment by ryneeverett** [comment]
There have been several updates to the database synchronization over the last 5 years which have hopefully made this obsolete -- more reliable identification of existing tasks, reopening of closed tasks, etc.
