### ISSUE TITLE
ServiceNow support

### ISSUE THREAD

**Issue by toddnni** [ralphbean/bugwarrior#507]
Has anyone started working on ServiceNow (https://www.servicenow.com/) support? 

There seems to be examples in wiki, but haven't tried them yet
<http://wiki.servicenow.com/index.php?title=Table_API_Python_Examples>

If I get frustrated I could try to work on it,

**Comment by ispringle** [comment]
I use ServiceNow and taskwarrior. I have my own SNow integration for TW, but am currently looking to move my integration/hook into Bugwarrior as it seems to be a far more robust solution. I will attempt to tackle this.

**Comment by ryneeverett** [comment]
Going to close this (cleaning up the queue). However, do see #410 for anyone who wants to contribute this as a patch.
