### ISSUE TITLE
Don't include Phabricator URL in task description

### ISSUE THREAD

**Issue by ghost** [ralphbean/bugwarrior#511]
It would be nice if the Phabricator URL was not by default included in the task description, since it takes up precious space and makes the `task list` much less usable. The URL can easily be inspected using `task ${ID}`, if desired.

**Comment by pjf** [comment]
As a user I've found bugwarrior tends to be quite verbose with all its default task descriptions, so I've ended up configuring pretty much all of them.

While I've not used Phabricator before, I've had success with the following (each in their relevant parts of the config file):

```
trello.description_template = {{trellocard}}
gmail.description_template = Gmail: {{gmailsubject}}
github.description_template = {{githubrepo}}#{{githubnumber}} ({{githubshorttype}}) {{githubtitle}}
```

I'm not familiar with the Phabricator UDAs (although `task uda` likely is), but I imagine you could use them the same way to set the default description.

**Comment by ryneeverett** [comment]
This is not unique to phabricator. The relevant proposal would be changing the default description_template globally across all services. I'm not sure how much support such a proposal would get.

**Comment by urzds** [comment]
Thanks for that hint, @pjf! That would be an acceptable workaround.

I now set:
```
phabricator.description_template={{phabricatorid}} - {{phabricatortitle}}
```

Is it possible to make Bugwarrior resync all tasks, so the description gets updated according to these new settings?

**Comment by pjf** [comment]
> Is it possible to make Bugwarrior resync all tasks, so the description gets updated according to these new settings?

Alas I'm not sure on this, but I'd love to know too. :)
