### ISSUE TITLE
bugwarrior-pull for a specific target

### ISSUE THREAD

**Issue by tjaartvdwalt** [ralphbean/bugwarrior#513]
I would like to propose a new command line option to `bugwarrior-pull` to override the `targets` setting in `bugwarriorrc`

Here is my use case.

I have 2 targets `bugwarriorrc`

~~~ini
[bitbucket]
...
[gitlab]
...
~~~

`bitbucket` takes 20 seconds to complete but `gitlab` takes around 300 seconds (maybe this is the real problem). I just added a new bug to `bitbucket`, and want to start using it in a task.

It would be very useful if I could do:

~~~sh
bugwarrior-pull --targets bitbucket
~~~

**Comment by ryneeverett** [comment]
Not a bad idea but you might find your use case better served by the `--flavor` option. For instance you could have a `quick` flavor.

**Comment by tjaartvdwalt** [comment]
Thanks for the reply. `--flavor` can do exactly what I need :)
