### ISSUE TITLE
GitHub import broken?

### ISSUE THREAD

**Issue by AnotherKamila** [ralphbean/bugwarrior#520]
Hi,

I tried to set up GitHub import according to the [documentation](https://bugwarrior.readthedocs.io/en/latest/services/github.html), but bugwarrior-pull fails. The error output:

```
> bugwarrior-pull
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [my_github]
ERROR:bugwarrior.services:Worker for [my_github] failed: string indices must be integers
Traceback (most recent call last):
  File "/home/kamila/.local/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 506, in _aggregate_issues
    for issue in service.issues():
  File "/home/kamila/.local/lib/python2.7/site-packages/bugwarrior/services/github.py", line 411, in issues
    for repo in repos:
  File "/home/kamila/.local/lib/python2.7/site-packages/bugwarrior/services/github.py", line 378, in filter_repos
    if repo['owner']['login'] != self.username:
TypeError: string indices must be integers
INFO:bugwarrior.services:Done with [my_github] in 3.291599s
INFO:bugwarrior.services:Terminating workers
CRITICAL:bugwarrior.command:Aborted (critical error in target 'my_github')
```

This sounds to me like maybe GitHub API changed or something?

For reference, here is my config file:

```
[general]
targets = my_github

inline_links        = False
annotation_links    = True
annotation_comments = False
log.level = DEBUG

[my_github]
service = github
github.username = anotherkamila
github.login = anotherkamila
github.token = @oracle:eval:cat ~/.github-token
```

**Comment by AnotherKamila** [comment]
Well, I just `curl`ed the GitHub API and it seems to me that it does look the way it should. I have no idea what's happening here.

**Comment by AnotherKamila** [comment]
My apologies, it was a misconfiguration on my side: I had a comment on the username line, so it looked like `github.username = anotherkamila  # comment`, which of course ended up in the URL, to which github returned something weird that caused this very confusing error in bugwarrior.

**Comment by ryneeverett** [comment]
Ah, so the github API was returning an error and bugwarrior broke down at parsing the response? If you could share the response you were getting (status code, json, etc.) we could probably catch a broad class of configuration errors and raise a more helpful exception in cases like this.
