### ISSUE TITLE
Example config for jira.add_tags format is misleading

### ISSUE THREAD

**Issue by Tzrlk** [ralphbean/bugwarrior#525]
The documentation for [common service configuration options][1] states that the `SERVICE.add_tags` option is a comma-separated list, but the [example configuration][2] uses a space-separated list. If this was intentional, I'd suggest adding a csv format usage somewhere else, or chucking a comment in there. Tags with spaces in them are a bitch to deal with in taskwarrior.

from http://bugwarrior.readthedocs.io/en/latest/configuration.html
```
[jira_project]
service = jira
jira.base_uri = https://jira.example.org
jira.username = ralph
jira.password = OMG_LULZ
jira.query = assignee = ralph and status != closed and status != resolved
# Set this to your jira major version. We currently support only jira version
# 4 and 5(the default). You can find your particular version in the footer at
# the dashboard.
jira.version = 5
jira.add_tags = enterprisey work
```
I'm not sure why, but taskwarrior doesn't seem to escape the space, but treats it as though it were escaped anyway.

[1]: http://bugwarrior.readthedocs.io/en/latest/common_configuration.html#common-service-configuration-options
[2]: http://bugwarrior.readthedocs.io/en/latest/configuration.html

**Comment by ralphbean** [comment]
Looks like this was fixed in c87044c1f47dfee2183abc7e463c3157058f5107

Thanks for reporting!
