### ISSUE TITLE
BitBucket issue on OAuth login

### ISSUE THREAD

**Issue by Mte90** [ralphbean/bugwarrior#537]
In my bugwarrior file:

```
[bitbucket]
service = bitbucket
bitbucket.assignee = mte90
bitbucket.username = mte90
bitbucket.login = mte90
bitbucket.key = xxxxxxxx
bitbucket.secret = xxxxx
bitbucket.password = xxxxxxxx
```

If I try to login I get:
```
INFO:bugwarrior.services:Working on [bitbucket]
ERROR:bugwarrior.services:Worker for [bitbucket] failed: 'refresh_token'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bugwarrior/services/__init__.py", line 504, in _aggregate_issues
    service = get_service(service_name)(conf, main_section, target)
  File "/usr/lib/python3/dist-packages/bugwarrior/services/bitbucket.py", line 99, in __init__
    response['refresh_token'])
KeyError: 'refresh_token'
INFO:bugwarrior.services:Done with [bitbucket] in 0.974141s
INFO:bugwarrior.services:Terminating workers
CRITICAL:bugwarrior.command:Aborted (critical error in target 'bitbucket')
```

Seems that error happen because the OAuth data are not valid but I generated them. If I use the auth with user/pass there are no problem but I cannot get the assigned tickets on my account.
So I tried with OAuth without any success.

**Comment by ryneeverett** [comment]
If you can debug I'd inspect that `response` object. It likely errored due to misconfiguration or a bitbucket API change.

Regardless, we should improve our logging to dump response data when non-200 responses are received.

**Comment by Mte90** [comment]
I done a little bit of debugging, the body say about errors on username/password.

**Comment by Mte90** [comment]
I got it bitbucket for login doesn't want the nickname but the email, and now is working!
