### ISSUE TITLE
GitLab issue on assigned task

### ISSUE THREAD

**Issue by Mte90** [ralphbean/bugwarrior#538]
In my bugwarrior:
```
[gitlab]
service = gitlab
gitlab.gitlabassignee = Mte90
gitlab.token = xxxxxxxxx
gitlab.login = Mte90
gitlab.host = gitlab.com
```
I have different tasks on private repos on gitlab but with access I cannot get only the ones assigned to me.
I am missing something? looking at the code seems that `only_if_assigned` is not used for gitlab.

**Comment by Mte90** [comment]
any updates for it?
I cannot use taskwarrior without a fix :-(

**Comment by urzds** [comment]
In my experience `gitlab.only_if_assigned = True` does work. Could you please elaborate further what the actual problem is? I am not sure I fully understand what bug you are facing.

**Comment by Mte90** [comment]
If i put `only_if_assigned` from gitlab is empty, if I remove show all my ticket opened also where I am already assigned.

**Comment by devurandom** [comment]
I'll try to recap:
* You do not have any of `gitlab.include_repos`, `gitlab.include_regex`, `gitlab.exclude_repos`, `gitlab.exclude_regex` set?
* When you clear the taskwarrior DB and set `gitlab.only_if_assigned = Mte90` in the `[gitlab]` section of your bugwarrior config, no tasks will be added by `bugwarrior-pull --dry-run`?
* When you clear the taskwarrior DB and remove `gitlab.only_if_assigned` from the `[gitlab]` section of your bugwarrior config, all tasks of the whole gitlab.com will be added by `bugwarrior-pull --dry-run`?

Is my understanding correct?

From reading the code [1], I believe there is no config key `gitlab.gitlabassignee`. Try removing it from your config.

[1]: https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/gitlab.py

**Comment by Mte90** [comment]
Yes everything right.
I am trying now with:
```
[gitlab]
service = gitlab
gitlab.assignee = mte90
gitlab.username = mte90
gitlab.token = xxxxxxxxxxxxxx
gitlab.login = Mte90
gitlab.host = gitlab.com
```

And take all the tickets that are not assigned to me but with `only_if_assigned` works everything. Without `gitlabassignee` isworking everything, seems that reading the code confused me!
