### ISSUE TITLE
Working around github abuse rate limits

### ISSUE THREAD

**Issue by jvehent** [ralphbean/bugwarrior#540]
While trying to use bugwarrior to pull issues and PRs from a handful of organisations, I continuously run into this error:

`OSError: Non-200 status code 403; 'https://api.github.com/repos/SOMEORG/SOMEREPO/issues/282/comments?per_page=100'; '{\n  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",\n  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."\n}\n'`

As far as I can tell, the only available workaround is to severely limit the number of repository I pull from. I was wondering if bugwarrior could have a configurable delay instead, while would add a few milliseconds between each API call to avoid running into this issue.

**Comment by decentral1se** [comment]
Hmmmm, yes, relying on `github.include_repos` to keep the request amount low.

**Comment by ryneeverett** [comment]
Nobody has reported this as an issue for a while and I suspect this problem doesn't exist any more. The authenticated [rate limit](https://docs.github.com/en/rest/reference/rate-limit) is typically 5000 at the moment (admittedly for an unknown period of time). We're paginating at the maximum 100 issues per request. I don't think anybody wants to pull over 500,000 issues. More likely is you're running bugwarrior too frequently and there's nothing we can do about that.
