### ISSUE TITLE
allow user-defined matchers to match tasks against multiple fields/UDAs

### ISSUE THREAD

**Issue by wookietreiber** [ralphbean/bugwarrior#545]
When using e.g. GitHub or GitLab services, I would like to match on a UDA. For both of these services, there are UDAs, e.g. **Github URL** or **Gitlab URL**, one could use to define custom task matchers.

I propose to extend the issue matching framework to include user-defined fields to match on, e.g. I would define my matcher to match not only on description (because that may change) but on some combination of description, issue id (not iid), url, etc.

What do you think about this?

**Comment by ryneeverett** [comment]
When you say "match", you mean selection of the issue to be included as a task, right?

For github, it doesn't seem like this would enable any more fine-grained control than provided by `github.query`, but I can see where it would provide a more consistent API across services.

**Comment by wookietreiber** [comment]
Sorry, *match* is a bit ambiguous. I do not mean filtering/selecting. I mean the way the way tasks are identified to be the same during the `bugwarrior-pull` synchronization.

**Comment by ryneeverett** [comment]
I don't see a use case for configuration because it seems like we can and do disambiguate tasks based on the `UNIQUE_KEY` values defined for each service. The `legacy_matching` based on description is indeed faulty and now disabled by default.

**Comment by wookietreiber** [comment]
I wasn't aware of `UNIQUE_KEY`, thanks for letting me know.
