### ISSUE TITLE
Gmail integration docs not rendered correctly

### ISSUE THREAD

**Issue by djmitche** [ralphbean/bugwarrior#546]
This should be relatively easy to fix, for someone who knows rST:

![screenshot-2018-2-20 gmail bugwarrior 0 8 0 documentation](https://user-images.githubusercontent.com/28673/36451946-ad3344f2-1660-11e8-8658-e343b2d2bce5.png)

**Comment by ryneeverett** [comment]
Somewhere along the line this was fixed.
