### ISSUE TITLE
gitea: support gitea (and maybe gogs)

### ISSUE THREAD

**Issue by genofire** [ralphbean/bugwarrior#573]
See swagger comments:
- https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/issue.go
- https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/pull.go

**Comment by ralphbean** [comment]
Going to close this (cleaning up the queue). However, do see #410 for anyone who wants to contribute this as a patch.
