### ISSUE TITLE
GitLab issue label -> Taskwarrior task priority mapping support

### ISSUE THREAD

**Issue by ghost** [ralphbean/bugwarrior#574]
Currently, the Bugwarrior GitLab service [does not support to set priorities based on the issue](https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/gitlab.py#L135-L137). It would be nice if GitLab issue labels could be mapped to Taskwarrior task priorities.

**Comment by ryneeverett** [comment]
I don't think any services currently provide dynamic priority assignment. Given that [priority is being phased out in favor of UDA's](https://taskwarrior.org/docs/priority.html) I wouldn't bother. You can set `gitlab.import_labels_as_tags = True` and then adjust the coefficients of your tags as needed.

**Comment by devurandom** [comment]
Thanks for the referral to the priority attribute being deprecated in favour of UDAs. This will make many things much easier. I propose to close this issue.
