### ISSUE TITLE
GitLab labels are mentioned as numbers in task description

### ISSUE THREAD

**Issue by ghost** [ralphbean/bugwarrior#575]
In the description of tasks imported from GitLab using bugwarrior, I see change log lines like `added ~57 ~64 and removed ~55 labels`. I would prefer if the actual label text would be displayed instead.

**Comment by urzds** [comment]
I believe this is actually a bug, not just a missing feature.

**Comment by ralphbean** [comment]
Closing as @ghost is now a deleted user.
