### ISSUE TITLE
various services: use created at as entered date

### ISSUE THREAD

**Issue by wookietreiber** [ralphbean/bugwarrior#578]
The title says it all: I would like to use the `created_at` fields from e.g. the GitHub API or the GitLab API as the entered date in taskwarrior (probably other services have such a field, too).

This may be optional, i.e. there could be an option to let the user choose:

1.  entered date (tw) is date bw entered the issue in tw (current behavior)
2.  entered date (tw) is date the issue was created in tool X

---

I would generally prefer the 2nd option because:

1.  I use the age of an issue for my urgency
2.  features like the burndown charts are inaccurate with the current bw behavior

---

**edit:** I changed title and description to **various services** because not just GitHub but others have such a field in their API. All services that provide such a created at date field should have this behavior / option.

**Comment by pawamoy** [comment]
This should be closed, right? Also see #620 and #621 for using the closing date as the `end` value.

**Comment by wookietreiber** [comment]
I only added support for GitHub and GitLab. Other services are not handled yet.

**Comment by pawamoy** [comment]
Ah yes indeed I see that now, thanks.

**Comment by ryneeverett** [comment]
triage: This is starting to look stale. There's *a lot* of inconsistency in behavior across services and these kinds of issues tend to be inactionable since only users of the services can test (and in some cases discover) the apis.
