### ISSUE TITLE
github: mismatch between docs and behaviour

### ISSUE THREAD

**Issue by TheKevJames** [ralphbean/bugwarrior#598]
[The docs say](https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/docs/services/github.rst#repo-owner) that `github.username` is only required unless `github.query` is set, but [the code disagrees](https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/github.py#L467-L468) and fails if `github.username` is missing even if `github.query` is set.

This sort of makes sense, since the default behaviour of having a `github.query` seems to be to _merge_ it with the results of `github.include_user_issues` and `github.include_user_repos` (if either or both are enabled) rather than disabling those fields and doing _only_ a query.

Not sure if the docs should be updated to reflect this or if the code should be updated to behave a bit more in-line with the docs. Some options that feel a bit more intuitive to me:
- if `github.query` is set, disable `github.include_user_issues` and `github.include_user_repos` by default
- if `github.query` is set, and `github.include_user_issues` and `github.include_user_repos` are both `False`, do not require a `github.username` to be set

**Comment by ryneeverett** [comment]
Our configuration validation was overhauled and it appears that this was fixed somewhere along the way. The service should succeed if you've specified either `github.username` or `github.query`.
