### ISSUE TITLE
gitlab api v3 no longer supported;

### ISSUE THREAD

**Issue by b08x** [ralphbean/bugwarrior#603]
I setup a new instance of bugwarrior to pull down tasks from a local container running GitLab Community Edition 11.0.3 aa62075

Bugwarrior version: 1.4.0+git2017010601-1 (installed from deb package)

`OSError: Non-200 status code 410; 'http://lab.loaf.org/api/v3/projects?page=1&per_page=100'; '{"error":"API V3 is no longer supported. Use API V4 instead."}'`

I updated /usr/lib/python3/dist-packages/bugwarrior/services/gitlab.py to replace all references of v3 to v4 and everything worked ok

**Comment by ryneeverett** [comment]
The latest release (1.6) supports gitlab api v4. I'm sorry if the debian distribution is out of date but I don't think there is anything we can do about that here.
