### ISSUE TITLE
[RFE] Load password / token variables in by environment variable

### ISSUE THREAD

**Issue by jwflory** [ralphbean/bugwarrior#606]
# Summary

Optionally load a service password / token by environment variable in addition to reading from the config file

# Background

I was setting up Bugwarrior and wanted to store my configuration file in my public dotfiles repository with my other config files. I don't want to put a password or token into my config file, but I'd like to be able to seamlessly sync the configuration between my multiple machines like my other dotfiles.

# Details

Use an environment variable for each platform (e.g. `BW_GITHUB_TOKEN` / `BW_GITHUB_PASSWORD`) to load a password if one is not specified in the configuration file.

# Outcome

Configurations can be more easily shared and seen by others without storing a secret string in the config file

**Comment by jwflory** [comment]
Never mind, I see this can be done with [eval](https://bugwarrior.readthedocs.io/en/latest/common_configuration.html#password-management) for password strings. Closing this issue.

**Comment by danihodovic** [comment]
@jwflory Does this work Github tokens? Could you provide an example?
