### ISSUE TITLE
gitlab keeps fetching projects forever

### ISSUE THREAD

**Issue by Valodim** [ralphbean/bugwarrior#612]
Using this config:

```
[gitlab_valodim]
service = gitlab
gitlab.login = Valodim
gitlab.token = TOKEN
gitlab.host = gitlab.com
gitlab.include_repos = nonpublic/internal

gitlab.only_if_assigned = True
gitlab.include_todos = True
```

I get this debug output:

```
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [gitlab_valodim]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects?page=1&per_page=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects?page=2&per_page=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects?page=3&per_page=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects?page=4&per_page=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects?page=5&per_page=100 HTTP/1.1" 200 None
```

I've let it run for a very long time (minutes) and it just keeps incrementing the page counter. I've varied some of the settings, but none of them seem to make a difference, except for `gitlab.token` which causes an unauthorized error if I flip a bit. In my gitlab there are only 10 or so repositories under "Your Projects / All", so it's not that I have ridiculous amounts of repositories either.

This is on bugwarrior-1.6.0, installed from pip.

**Comment by logankoester** [comment]
This is happening for me too, both from pip and also with both `master` and `develop` branches from git.

**Comment by plup** [comment]
I confirm I have the same issue with giltab.com. I have only 2 projects and less than 5 issues and it hangs for hours before I kill it.

**Comment by pawamoy** [comment]
I remember, when playing with GitLab API, that it was sometimes counter-intuitive. You had to download entire, big lists of repositories before being able to filter, or something like that.

Here the requested API URL is `GET /api/v4/projects?page=31&per_page=100`, so of course if you hit gitlab.com, it will take forever to download all the pages.

I think we should use the following URL instead: `GET /users/:user_id/projects`. It would greatly reduce the size and number of downloaded pages (and therefore make it work for gitlab.com), but also it would be more consistent with the github service: for github you get only the repositories for the given `github.username`. This change would add the `gitlab.username` variable as well in gitlab service.

**Comment by ghtmtt** [comment]
I can also confirm this issue. See related #616

**Comment by doronbehar** [comment]
Has anyone tested this fix and confirmed it works now for him? On my side the pull process still takes for ever..

**Comment by ralphbean** [comment]
Yes, @gustavoheinz tested it.

Have you tried setting `gitlab.membership = True` @doronbehar?

**Comment by doronbehar** [comment]
No. With `gitlab.membership = True` it works. But why? My GitLab configurations is this:
```
[my_gitlab]
service = gitlab
gitlab.host = gitlab.com
gitlab.login = doronbehar
gitlab.token = @oracle:eval:gopass show -f api/gitlab
gitlab.include_todo = True
```

If I have to add `gitlab.membership = True` then does this mean that I can't retrieve TODOs unless I'm the member in the repositories of those issues / merge requests ?

**Comment by ralphbean** [comment]
Ah, looks like we need a patch to restore support for `include_all_todos` vs `include_todos` here.
