### ISSUE TITLE
Error with gitlab download

### ISSUE THREAD

**Issue by ghtmtt** [ralphbean/bugwarrior#616]
Hi, I'm experiencing this error with gitlab:

```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [my_gitlab]
ERROR:bugwarrior.services:Worker for [my_gitlab] failed: Non-200 status code 410; 'https://gitlab.com/api/v3/projects?page=1&per_page=100'; '{"error":"API V3 is no longer supported. Use API V4 instead."}'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bugwarrior/services/__init__.py", line 506, in _aggregate_issues
    for issue in service.issues():
  File "/usr/lib/python3/dist-packages/bugwarrior/services/gitlab.py", line 402, in issues
    all_repos = self._fetch_paged(tmpl)
  File "/usr/lib/python3/dist-packages/bugwarrior/services/gitlab.py", line 329, in _fetch_paged
    items = self._fetch(tmpl, params=params)
  File "/usr/lib/python3/dist-packages/bugwarrior/services/gitlab.py", line 318, in _fetch
    return self.json_response(response)
  File "/usr/lib/python3/dist-packages/bugwarrior/services/__init__.py", line 485, in json_response
    response.status_code, response.url, response.text,
OSError: Non-200 status code 410; 'https://gitlab.com/api/v3/projects?page=1&per_page=100'; '{"error":"API V3 is no longer supported. Use API V4 instead."}'
INFO:bugwarrior.services:Done with [my_gitlab] in 0.657924s
INFO:bugwarrior.services:Terminating workers
CRITICAL:bugwarrior.command:Aborted (critical error in target 'my_gitlab')
```

nothing else than:

* user
* token
* repo
* host

as described in the docs. Is this a bug or am I missing some configuration detail?

Thanks

**Comment by philall** [comment]
> Hi, I'm experiencing this error with gitlab:
> 
> ```
> INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
> INFO:bugwarrior.services:Starting to aggregate remote issues.
> INFO:bugwarrior.services:Spawning 1 workers.
> INFO:bugwarrior.services:Working on [my_gitlab]
> ERROR:bugwarrior.services:Worker for [my_gitlab] failed: Non-200 status code 410; 'https://gitlab.com/api/v3/projects?page=1&per_page=100'; '{"error":"API V3 is no longer supported. Use API V4 instead."}'
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/bugwarrior/services/__init__.py", line 506, in _aggregate_issues
>     for issue in service.issues():
>   File "/usr/lib/python3/dist-packages/bugwarrior/services/gitlab.py", line 402, in issues
>     all_repos = self._fetch_paged(tmpl)
>   File "/usr/lib/python3/dist-packages/bugwarrior/services/gitlab.py", line 329, in _fetch_paged
>     items = self._fetch(tmpl, params=params)
>   File "/usr/lib/python3/dist-packages/bugwarrior/services/gitlab.py", line 318, in _fetch
>     return self.json_response(response)
>   File "/usr/lib/python3/dist-packages/bugwarrior/services/__init__.py", line 485, in json_response
>     response.status_code, response.url, response.text,
> OSError: Non-200 status code 410; 'https://gitlab.com/api/v3/projects?page=1&per_page=100'; '{"error":"API V3 is no longer supported. Use API V4 instead."}'
> INFO:bugwarrior.services:Done with [my_gitlab] in 0.657924s
> INFO:bugwarrior.services:Terminating workers
> CRITICAL:bugwarrior.command:Aborted (critical error in target 'my_gitlab')
> ```
> nothing else than:
> 
> * user
> * token
> * repo
> * host
> 
> as described in the docs. Is this a bug or am I missing some configuration detail?
> 
> Thanks

update bugwarrior. you version don't support gitlab API V4.

**Comment by ghtmtt** [comment]
One step further, thanks! I have now a conflict with future:

```
matteo@debian:~/.config/bugwarrior$ pip show future
Name: future
Version: 0.16.0
Summary: Clean single-source support for Python 3 and 2
```

and I think I cannot downgrade it because other dependencies..

```matteo@debian:~/.config/bugwarrior$ bugwarrior-pull 
Traceback (most recent call last):
  File "/usr/local/bin/bugwarrior-pull", line 11, in <module>
    sys.exit(pull())
  File "/home/matteo/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/matteo/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/matteo/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matteo/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/command.py", line 62, in pull
    config = _try_load_config(main_section, interactive)
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/command.py", line 35, in _try_load_config
    return load_config(main_section, interactive)
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/config.py", line 219, in load_config
    validate_config(config, main_section)
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/config.py", line 177, in validate_config
    if not get_service(service):
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/services/__init__.py", line 41, in get_service
    return epoint.load()
  File "/home/matteo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/home/matteo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/matteo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (future 0.16.0 (/home/matteo/.local/lib/python3.6/site-packages), Requirement.parse('future!=0.16.0'))
```

**Comment by ghtmtt** [comment]
Hi,

I think the setup is OK but the connection is looping forever and not pulling anything. This is the looping message (after 30 minutes is always the same):

```
matteo@debian:~$ bugwarrior-pull 
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [matteo_gitlab]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects?page=1&per_page=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com
```

**Comment by pawamoy** [comment]
Yes, see #612. API requests must be modified in some way. Currently the code will download the entire base of projects on gitlab.com, this is why it seems like it's looping forever.

**Comment by ghtmtt** [comment]
@pawamoy I did not see that issue. Thanks for cross referencing. Closing this as a duplicate
