### ISSUE TITLE
Feature Request: Trello checklists support

### ISSUE THREAD

**Issue by artur-shaik** [ralphbean/bugwarrior#617]
It can be useful if checklists created as subtasks of card task in taskwarrior. What you think?

**Comment by ralphbean** [comment]
Ah, there's not much of a sub-task concept in taskwarrior itself.  I'm not sure how we'd map it.

I guess we could create multiple taskwarrior tasks, one for each of the checklist items and then mark the parent task as depending on those sub-tasks?

**Comment by ralphbean** [comment]
Although, that opens up a can of worms for sub-task and dependency support for all the other backends as well.  Hm - it's a neat idea, but I'm not sure I'm open to supporting that longer term.

I'm going to close this one.  Thanks for submitting the idea @artur-shaik!
