### ISSUE TITLE
What are hooks used for? There is no example or explanation in the docs

### ISSUE THREAD

**Issue by pawamoy** [ralphbean/bugwarrior#619]
Can a hook be a Python script? Are data passed to the script? Is it expected to output data?

**Comment by pawamoy** [comment]
OK so I guess the main use-case for hooks is to backup the data. I was a bit confused because Taskwarrior itself provides hooks so I thought maybe they were similar, but no :slightly_smiling_face: Thank, you can close this issue if you want!

**Comment by ralphbean** [comment]
Thanks.  :)
