### ISSUE TITLE
GitLab issue: summary

### ISSUE THREAD

**Issue by pawamoy** [ralphbean/bugwarrior#624]
There are currently a few issues and pull requests about the GitLab service being really too slow and bandwidth expensive for large instances. I intend to summarize them in this one, so we can combine efforts and eventually fix it :slightly_smiling_face:. This should also allow to clean up by closing duplicate issues and PRs that won't be merged / that are not ready and not updated anymore.

### Issues
- #551 "Pulling from gitlab is very slow", opened April 4, 2018.
  Proposes to use something like `/issues?scope=assigned-to-me`.
  Could simply be closed as duplicate, in favor for more recent, commented issues.
- #590 "gitlab: reduce number of api requests", opened July 4, 2018.
  Proposes to play with `assignee` parameter to reduce API calls.
- #612 "gitlab keeps fetching projects forever", opened October 2, 2018.
  Acknowlegments of the issue by multiple users.
  Proposition, by myself, to be consistent with GitHub service and introduce a `gitlab.username` to be used in `/users/:user_id/projects`.

### Pull Requests
- #593 "gitlab: reduces issue and merge request api calls", opened July 5, 2018.
  PR for issue #590. Only works with `gitlab.only_if_assigned = username`
  and `gitlab.also_unassigned = False`. It is said to fail in this [comment](https://github.com/ralphbean/bugwarrior/pull/593#issuecomment-418444140) (Sep 4), and has not been updated since.
- #613 "Update gitlab service to correct project request", opened October 3, 2018.
  Makes use of `owned` and `membership` parameters.
  Redundancy [noted](https://github.com/ralphbean/bugwarrior/pull/613#issuecomment-430335559) by @wookietreiber between those two parameters.
  Also uses `simple` flag to reduce size of data returned by the API :+1:.
  Adds `configparser` to `setup.py`, which is now extraneous since #618 was merged.

---

I'm proposing a step-by-step list to fix this.

1. check the API docs to determine the best way to improve the service (reduce API calls number, reduce data size, reduce execution time), **with current service configuration options** (-> without adding stuff). Maybe some simple tweaks could rapidly be merged, without resorting to new config options or refactors. We already know one: the `simple` flag.
2. redesign the way the service should pull issues by checking what the API offers: instead of getting all projects, then filter, then get issues for these projects, etc., maybe we can get the users projects, or the projects they contribute to, then the associated issues, etc., or maybe we can immediately get the issues where the user is involved, etc. I'm sure there are a lot of ways to do this, but there must be one that is obvious and efficient.
3. refactor the service and its configuration options to implement the design chosen in step 2.

That's it, let me know what you think before I start working on this!

#### A few mentions
@ralphbean as you are the owner of this repo
@ryneeverett as you are a maintainer? (you added tags to issues :wink:)
@wookietreiber as you contributed and reviewed many things
@mathstuf as you initially contributed support for GitLab
@carlitux as you contributed a PR
@Valodim as you reviewed related PRs

**Comment by ryneeverett** [comment]
Performance improvements that don't alter behavior or significantly impact maintainability are appreciated.

**Comment by mathstuf** [comment]
GitLab is starting to do GraphQL. Probably easiest if we just move to that once widely available.

**Comment by ralphbean** [comment]
Thanks for the summary, @pawamoy!

We got to #613 via #649 today at the PyCon sprints.

Can someone report if it makes the experience sufficiently usable?  If not, we can pursue options for a refactor.  (An idea: we could add a new, second gitlab service with a different implementation and different behavior if we can't find an acceptable migration path in the existing service.  Users could choose to use this new one and perhaps someday we deprecate the current one.)

**Comment by renestalder** [comment]
@ralphbean So I got bugwarrior 1.7.0. I'm still facing issues that getting the data takes forever. Interesting enough, It works for a self-hosted GitLab instance (takes around 40 seconds), but not for gitlab.com (never finishes).

My configuration is as simple as that, on macOS:

```
[gitlab_com]
service = gitlab
gitlab.host = gitlab.com
gitlab.login = renestalder
gitlab.token = @oracle:eval:security find-generic-password -s gitlab_com_token -w
```

**Edit**:

Maybe the log that is shown when I abort the whole process helps you somehow:

```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [gitlab_com]
^C
Aborted!
ERROR:bugwarrior.services:Worker for [gitlab_com] failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
    for issue in service.issues():
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/gitlab.py", line 482, in issues
    all_repos = self._fetch_paged(tmpl + '?' + urlencode(querystring))
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/gitlab.py", line 377, in _fetch_paged
    items = self._fetch(tmpl, params=params)
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/gitlab.py", line 364, in _fetch
    response = requests.get(url, headers=headers, verify=self.verify_ssl, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
INFO:bugwarrior.services:Done with [gitlab_com] in 800.105034s
```

**Comment by ryneeverett** [comment]
All of the original issues have been resolved. I've opened #905 to track the only remaining concrete suggestion for improving gitlab performance.
