### ISSUE TITLE
Override project of pulled tasks (in Jira)

### ISSUE THREAD

**Issue by TMiguelT** [ralphbean/bugwarrior#636]
It seems that we can add additional tags to pulled tasks with something like `jira.add_tags = enterprisey,work`. However, with my JIRA tasks, the project is auto-assigned to be the JIRA project the tasks were pulled from. However I would like to be able to combine multiple JIRA projects into one TaskWarrior project ("Work"). Is this possible?

**Comment by ralphbean** [comment]
It should be possible today, yes.

See https://bugwarrior.readthedocs.io/en/latest/common_configuration.html#field-templates

You should be able to set the project template to a "hard coded" string, like:

```
jira.project_template = WorkWork
```
