### ISSUE TITLE
Annotations have newlines stripped

### ISSUE THREAD

**Issue by mattcen** [ralphbean/bugwarrior#637]
Is there any reason why Bugwarrior strips newlines out of annotations?

I've just commented out [this line](https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/__init__.py#L151):
` message = message.replace('\n', '').replace('\r', '')`
and confirmed that Taskwarrior annotations permit newline characters within them, and I'd like them to remain, but I'm just wondering if there's a good reason they're being removed.

If not, add a config option to change this behaviour?

**Comment by ralphbean** [comment]
You know... I think back in the day I just wanted my annotations to appear on a single line, but I see that maybe this isn't what everone wants.  I'm open to make a config option for it.  :)

**Comment by mattcen** [comment]
Thanks so much, @ralphbean; that's excellent!
