### ISSUE TITLE
Invalid ID when pulling from trello

### ISSUE THREAD

**Issue by sliptonic** [ralphbean/bugwarrior#639]
I'm trying to configure trello integration  for the first time.  I followed the documentation at https://bugwarrior.readthedocs.io/en/latest/services/trello.html as best I could.
FYI, in the section on trello.token it says 'see below for how to get it' but there's nothing below.
So I muddled through on the trello site to generate a token and used that.  

But when I try to sync, I get the following error (key and token redacted):

OSError: Non-200 status code 400; 'https://api.trello.com/1/boards/Stuff?fields=name&key=XXXMyKeyXXX&token=XXXMyTokenXXX'; 'invalid id'

**Comment by ralphbean** [comment]
@gdetrez, can you help @sliptonic out here?

**Comment by gdetrez** [comment]
@sliptonic I can reproduce by using an invalid id in `trello.include_boards`.  Looking at the url in the error message it seems that you're trying to use the board name ("Stuff") in place of the board id.

**Comment by ralphbean** [comment]
Thanks @gdetrez - I figure this can be closed.
