### ISSUE TITLE
Feature Request: Clubhouse.io support

### ISSUE THREAD

**Issue by huntrar** [ralphbean/bugwarrior#640]
title

**Comment by ralphbean** [comment]
Sounds good.  :)

I think we're not accepting new RFEs currently to add new backends *unless* someone can come forward with a pull request to add it.  If you're up to coding it, we'll likely accept it.  It comes with one condition though:  there are too many backends for us to maintain expertise in all of them.  To get merged, we hope you'll stay around to help field bug reports on the clubhouse.io backend.

I'll close this for now, but if you (or anyone) wants to produce a PR to add this, fire away!

**Comment by jkaiser-ioki** [comment]
@huntrar : Are you planning to follow up on this and/or is https://github.com/huntrar/clubwarrior still actively maintained? (Also in light of the recent name change from Clubhouse to Shortcut). My company actively uses Shortcut [prev. Clubhouse] and I am using Taskwarrior on my Arch Linux and would love to somehow sync those Shortcut stories into my task list.

I am a dev at heart, but Python is not really my strong suit, so I am not sure if I could take over any major responsibility here. Still, if there is something to move this forward somehow I can try to give it a shot :-)

**Comment by huntrar** [comment]
Ah, thanks for letting me know there is interest. I will follow up on this when I have more free time. In the interim I wouldn't advise using clubwarrior in a production environment, it was working fairly well when I left it but I can no longer guarantee its safety. If you did choose to use it, pointing the `BASE_URL` to the new Shortcut API locator would probably get it running again.

When I revisit the project I will see that it is a backend to bugwarrior rather than a standalone piece.
