### ISSUE TITLE
Add notification option to execute a script with the message

### ISSUE THREAD

**Issue by jerri** [ralphbean/bugwarrior#641]
I would like to execute a script with the messages created from bugwarrior, to do some alternative notification. Suggestion would be something like

~~~
[notification]
backend=script
script_template='/path/to/script $message'
~~~

or is there a different approach available to do this. My use case is, I am fully working via ssh on a remote server without any X content. So notifications about new/modified bugs currently can't be shown anywhere.

**Comment by ralphbean** [comment]
Have you looked at taskwarrior hooks?  That should be able to do it for you.

https://taskwarrior.org/docs/hooks_guide.html
