### ISSUE TITLE
any new releases?

### ISSUE THREAD

**Issue by eirnym** [ralphbean/bugwarrior#660]

**Comment by ralphbean** [comment]
I woke up after being dormant on this project for over a year.  Yes, we can cut a release soon.  :)

**Comment by eirnym** [comment]
I hope for faster releases than once a year

**Comment by ralphbean** [comment]
Working out of our git repo can give you that.  Try

```
pip install git+https://github.com/ralphbean/bugwarrior#egg=bugwarrior
```

**Comment by eirnym** [comment]
I prefer to have releases instead of pulling a branch with uncontrollable compatibility.

**Comment by pawamoy** [comment]
@eirnym New releases require bugfixes and/or new features. Don't hesitate to contribute if you'd like the project to move forward faster ;) !

**Comment by eirnym** [comment]
I agree with you :)

**Comment by koobs** [comment]
Welcome back @ralphbean!

**Comment by ralphbean** [comment]
Give [bugwarrior-1.7.0](https://pypi.org/project/bugwarrior/) a try.

Thanks to all who sent patches!
