### ISSUE TITLE
Default priorities not being set

### ISSUE THREAD

**Issue by Fubukimaru** [ralphbean/bugwarrior#665]
Hello!

First of all, thank you for your work. I find this application perfect for my workflow :).

I have a couple of github accounts plus a trello account with different priorities set, however the new task always get the global default 'M'. For trello I have tried the following:
```
trello.default_priority = L
```
```
trello.default_priority = 'L'
```

Am I missing something?

Thanks!

**Comment by Fubukimaru** [comment]
I had bugwarrior version 1.6. Works correctly.

**Comment by ralphbean** [comment]
\ó/

**Comment by Fubukimaru** [comment]
It is not going to happen again, sorry! :dancer:

**Comment by ralphbean** [comment]
Cheers :)
