### ISSUE TITLE
What is your license?

### ISSUE THREAD

**Issue by amb1s1** [ralphbean/bugwarrior#673]
Any reason why you guys don't have a license in your repo?

**Comment by aklt** [comment]
There is a LICENSE file which states that this project is licensed under
GNU General Public License v3.0.

(I am not a contributer to this project, just noticed your issue)

**Comment by ralphbean** [comment]
Yeah, I think we're good to go.  If you're looking for the license somewhere we're not thinking of, let us know @amb1s1.  Happy hacking!
