### ISSUE TITLE
Bugzilla XML-RPC API to be deprecated, please switch to REST API

### ISSUE THREAD

**Issue by emceeaich** [ralphbean/bugwarrior#697]
[We are removing the XML-RPC API](https://bugzilla.mozilla.org/show_bug.cgi?id=1599274). Please see documentation at https://bmo.readthedocs.io/en/latest/api/index.html.

**Comment by djmitche** [comment]
Is this being removed from upstream bugzilla, or just from the Mozilla instance?  At what version of Bugzilla was the REST interface introduced?

**Comment by dklawren** [comment]
> Is this being removed from upstream bugzilla, or just from the Mozilla instance? At what version of Bugzilla was the REST interface introduced?

From the BMO instance for now. Once we finish merging BMO code as the new upstream code it will be the same then. We introduced the REST API about mid 2013.

**Comment by djmitche** [comment]
Thanks!  So, @emceeaich I'll be able to start using this once it's released.

**Comment by emceeaich** [comment]
See https://groups.google.com/forum/#%21topic/mozilla.dev.platform/gDuH7RStS3c

@djmitche, is this a blocker for you on your projects?

**Comment by djmitche** [comment]
It will be when it's shut down, yes.
