### ISSUE TITLE
Increase Phabricator support

### ISSUE THREAD

**Issue by ghost** [ralphbean/bugwarrior#698]
It would be nice if the phabricator service was more like GitHub, using the project from phabricator instead of the service name on imported tasks.

**Comment by ghost** [comment]
I don't have any experience with Python in particular but am interested in trying to add this.

Any pointers? Is it a limitation of the python library `phabricator`?

**Comment by evilham** [comment]
It looks to me like this used to be implemented and is a bit of a regression, the places where it should be implemented are:
https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/phab.py#L186

**Comment by ryneeverett** [comment]
triage: This is starting to look stale. Anybody interested in addressing it?
