### ISSUE TITLE
DebianBTS: Eponymous Python module deprecated positional parameter support

### ISSUE THREAD

**Issue by RogueScholar** [ralphbean/bugwarrior#715]
Had to dive into my bugwarrior logfile thanks to Google being a turd recently, and was greeted mostly by the following:

```python
WARNING:debianbts.debianbts:Calling get_bugs with positional arguments is deprecated,
    please use keyword arguments instead.
INFO:pysimplesoap.client:POST https://bugs.debian.org/cgi-bin/soap.cgi
```

Criminey, there were a lot of those. A quick stroll through the [python-debianbts](https://tracker.debian.org/pkg/python-debianbts) Debian package [changelog](https://github.com/venthur/python-debianbts/blob/2.10.0/debian/changelog) led rather unambiguously to the entry for version 2.10.0 released the first of November, last year:

* Modernized a few awkward method calls:
    * Deprecated support for positional arguments in `get_status`, we use a
      list of bugnumbers explicitly now: `get_status(123, 234, 345)` becomes
      `get_status([123, 234, 345])`
    * Deprecated support for positional arguments in `get_usertags`, we use a
      list of tags explicitly now: 
      `get_usertags('mail@example.com', 'foo', 'bar')` becomes
      `get_usertags('mail@example.com', ['foo', 'bar'])`
    * Deprecated support for positional arguments in `get_bugs`, we use
      `kwargs` explicitly now: 
      `get_bugs('package', 'gtk-qt-engine', 'severity', 'normal')` becomes
      `get_bugs(package='gtk-qt-engine', severity='normal')`
    the old ways to call those methods will be supported for a while, but
    there will be deprecation warnings.

Who knows when those greybeards will pick a random Tuesday morning to yank the support for the old syntax without warning, so I thought I'd pass what I found along to you here.

In other news...freakin' sickmate add-on you've made here! Having everything aggregate in the terminal (which is almost as comfortable as the womb to me) instead of across a half-dozen web sites all taking pains to make their crop of "ugh..." look truly urgent has really lowered my anxiety levels, so thank you, truly. :+1: 

Regards,
Peter

**Comment by ryneeverett** [comment]
Fixed by #695.
