### ISSUE TITLE
Config file: unable to use env variables

### ISSUE THREAD

**Issue by BamBalaam** [ralphbean/bugwarrior#716]
Hi all,

It's either not documented or I'm very bad at parsing the docs: is there any way to use environment variables in the bugwarriorrc file? If not, is there a reason for this? And if not (again), can I try to have a go at introducing it into the code? :smile: 

Use-case: I version my config and dotfiles. I'd like to be able to use env variables to avoid exposing some URLs and account names (I've solved that issue for passwords by using the great `@oracle:eval:` command you have.

**Comment by ryneeverett** [comment]
Is this a common config file feature? Strikes me a rare use case.

**Comment by BamBalaam** [comment]
@ryneeverett It might not be super common on this type of software which is mostly run locally, but in many other software solutions it's quite abundant: [Docker Compose](https://docs.docker.com/compose/environment-variables/), [parts of the Elastic Stack](https://www.elastic.co/guide/en/beats/filebeat/current/using-environ-vars.html), [Flask](https://flask.palletsprojects.com/en/1.1.x/config/#configuring-from-environment-variables) and others.

I understand that the aim of bugwarrior is not the same as the examples I gave, but I feel like this feature would be a nice addition for the large amount of people storing their dotfiles online, [e.g. here on Github](https://github.com/search?q=dotfiles), helping them not to expose sensible data such as a private JIRA domain or a username when versioning their bugwarriorc file.

**Comment by ryneeverett** [comment]
Seems like this could be easily be implemented with a thin wrapper script, such as:

```sh
bugwarrior-pull () {
    echo "DO NOT EDIT. GENERATED FROM $HOME/.config/bugwarrior/bugwarriorrc-src!" > $HOME/.config/bugwarrior/bugwarriorrc
    # You may need to install gettext for the envsubst binary.
    envsubst < $HOME/.config/bugwarrrior/bugwarriorrc-src >> $HOME/.config/bugwarrior/bugwarriorrc
    exec /usr/bin/bugwarrior-pull "$@"
}
```



Unless this solution is inadequate or this feature is in popular demand I'd rather not add this functionality to bugwarrior itself.

**Comment by BamBalaam** [comment]
Okay 🙂 Closing this for now then.
