### ISSUE TITLE
Ideas Project  - The expression could not be evaluated

### ISSUE THREAD

**Issue by xeruf** [ralphbean/bugwarrior#724]
```
task add project:ide test
```
Reports: `The expression could not be evaluated.`

I wanted to add a task in an `ideas` project, but any project starting with `ide` automatically fails with the aforementioned error.

**Comment by ryneeverett** [comment]
This appears to be an issue with taskwarrior, not bugwarrior.

**Comment by xeruf** [comment]
Sorry, I don't know how I ended up here ^^
