### ISSUE TITLE
Integration with git-bug

### ISSUE THREAD

**Issue by jahagirdar** [ralphbean/bugwarrior#726]
Git-bug is a BTS integrated in git repo.

It will be useful to import bugs from git-bug and manage them from taskwarrior. see MichaelMure/git-bug#191 for details

**Comment by ryneeverett** [comment]
I don't understand the advantage at this point. It looks like they only support a fraction of the services we do.

**Comment by zarelit** [comment]
git-bug can be used without bridging to another BTS, so I think the issue is for having git-bug added as another service whose API is "mimic git-bug and read the bugs in the repository"

**Comment by ryneeverett** [comment]
Ah, now I get it. I would think we'd be able to use the git-bug graphql api that they use for the web frontend.

**Comment by zarelit** [comment]
Thanks @ryneeverett
