### ISSUE TITLE
Import Trello description

### ISSUE THREAD

**Issue by mattcen** [ralphbean/bugwarrior#727]
When syncing with Trello, we import the title of the card, and any comments get added as annotations. The Trello description, however, is not imported into TaskWarrior at all. This is kinda important. I'm not sure how best to store this into TaskWarrior. I can see in https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/trello.py#L45 that the TaskWarrior description is constructed from various fields, but it's unclear what the best way is to slot in the Trello description in there.

It could go before the URL, but that could push the URL several lines down.
It could be added as an Annotation, but that doesn't feel quite right either.

I'm happy to implement this, but am unsure of where to map the description into. Any opinion as to where it should go? If given a decision, I should be able to go ahead and create a PR.

**Comment by mattcen** [comment]
(This should be labelled "Trello" and "feature proposal")

**Comment by mattcen** [comment]
I think this patch should do the trick, but am getting a weird issue with task descriptions being too wide.
```
diff --git i/bugwarrior/services/trello.py w/bugwarrior/services/trello.py
index 48d81b1..e70e9d1 100644
--- i/bugwarrior/services/trello.py
+++ w/bugwarrior/services/trello.py
@@ -43,7 +43,7 @@ class TrelloIssue(Issue):
         """ Return the old-style verbose description from bugwarrior.
         """
         return self.build_default_description(
-            title=self.record['name'],
+            title=self.record['name'] + ('\n' + self.record['desc'] + '\n' if self.record['desc'] else ''),
             url=self.record['shortUrl'],
             number=self.record['idShort'],
             cls='task',
@@ -162,7 +162,7 @@ class TrelloService(IssueService, ServiceClient):
         """ Returns an iterator for the cards in a given list, filtered
         according to configuration values of trello.only_if_assigned and
         trello.also_unassigned """
-        params = {'fields': 'name,idShort,shortLink,shortUrl,url,labels,due'}
+        params = {'fields': 'name,idShort,shortLink,shortUrl,url,labels,due,desc'}
         member = self.config.get('only_if_assigned', None)
         unassigned = self.config.get('also_unassigned', False, asbool)
         if member is not None:
```
The too-wide issue seems to be sometimes related to a lack of trailing whitespace: https://gist.github.com/mattcen/e6e8b00fc4be4835f1c0e84e4d526fc8

**Comment by mattcen** [comment]
This looks like it was due to a wrapping bug in TaskWarrior. See https://github.com/GothenburgBitFactory/taskwarrior/issues/2263. The bug appears fixed in TW 2.6, meaning this patch shouldn't cause any long-term issues, though who knows when 2.6 will be released.

**Comment by ryneeverett** [comment]
Looks like this is addressed by #717.

**Comment by mattcen** [comment]
Oh, so it does; my apologies; I did look for existing issues/PRs, but obviously didn't look hard enough! Is this likely to be merged in any time soon?

**Comment by ryneeverett** [comment]
No need to apologize, it probably would have taken a lot longer had you not opened this issue as I'm hesitant to mess with the UDA's of services I don't personally use. I'll probably merge it in a few weeks if there's no more feedback.
