### ISSUE TITLE
default_priority = None fails, with misleading error message

### ISSUE THREAD

**Issue by Will-Shanks** [ralphbean/bugwarrior#729]
While attempting to set the priority of tasks to none I tried
```github.default_priority = None```
which fails with:
```Traceback (most recent call last):
  File "/home/shanks/.local/bin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.7.0', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/shanks/.local/lib/python3.8/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/home/shanks/.local/lib/python3.8/site-packages/bugwarrior/db.py", line 422, in synchronize
    new_task = tw.task_add(**issue)
  File "/home/shanks/.local/lib/python3.8/site-packages/taskw/warrior.py", line 665, in task_add
    task = self._stub_task(description, tags, **kw)
  File "/home/shanks/.local/lib/python3.8/site-packages/taskw/warrior.py", line 534, in _stub_task
    return Task.from_stub(task, udas=self.config.get_udas())
  File "/home/shanks/.local/lib/python3.8/site-packages/taskw/task.py", line 88, in from_stub
    processed[k] = cls._serialize(k, v, fields)
  File "/home/shanks/.local/lib/python3.8/site-packages/taskw/task.py", line 110, in _serialize
    return converter.serialize(value)
  File "/home/shanks/.local/lib/python3.8/site-packages/taskw/fields/choice.py", line 34, in serialize
    raise ValueError(
ValueError: 'None' is not a valid choice; choices: [None, 'H', 'M', 'L']
```

Which is confusing as None is said to be a valid choice. Improving this error message to better indicate that one should do ```service.default_priority = ``` not ```service.default_priority = None```  would remove this confusion, or None should be made a valid default_priority choice.

**Comment by Will-Shanks** [comment]
I'd be happy to submit a PR fixing this, but would like some guidance as to the best solution.
So far my ideas are:
1. Modify [this](https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/db.py#L331) if from
```
              # Blank priority should mean *no* priority
              if issue_dict['priority'] == u'':
                  issue_dict['priority'] = None
```
to
```
              # Blank priority should mean *no* priority
              if issue_dict['priority'] == u'' or issue_dict['priority'] == u'None':
                  issue_dict['priority'] = None
```
2.  Validate the option in config.py while reading in the config

I think option 2 is better, but don't want to think too hard about how best to do it if that won't be an excepted solution.

**Comment by Will-Shanks** [comment]
Or change [this](https://github.com/ralphbean/taskw/blob/11e2f9132eaedd157f514538de9b5f3b69c30a52/taskw/task.py#L43) line in taskw to be 
```choices=['', 'H', 'M', 'L', ],```

**Comment by ryneeverett** [comment]
What would you think about just improving the error message at the point where it was raised? https://github.com/ralphbean/taskw/blob/develop/taskw/fields/choice.py#L37

```diff
- _choices
+ ['' if c is None else c for c in _choices]
```

**Comment by Will-Shanks** [comment]
That sounds like a good solution to me. I'll send in a PR to the taskw repo.

**Comment by ryneeverett** [comment]
I'm thinking validating in config.py and raising an exception before it's passed to taskw would be better after all since there's no practical way to catch just this particular `ValueError` from taskw.

**Comment by Will-Shanks** [comment]
That's a good point.
It looks like there is already code in config.py that does some validation, I'll have a go finding a way to add validating ```service.default_priority``` in.

**Comment by ryneeverett** [comment]
`IssueService.validate_config` in bugwarrior/services/__init__.py might be the best place since that's where the service configuration options are validated.

**Comment by ryneeverett** [comment]
Perhaps `None` doesn't work any more or not with all services? See #795.

**Comment by ryneeverett** [comment]
Between #849, which should catch unacceptable values and give specific error messages, and #887, which allows an empty default priority, I think this has been resolved.
