### ISSUE TITLE
Asana support

### ISSUE THREAD

**Issue by thatnerdjosh** [ralphbean/bugwarrior#735]
Was just wondering if there are any plans to support asana, and if so, I could volunteer to build that integration out. One of my clients uses Asana so it would be great to be able to bring those tasks as well through to taskwarrior. Another option is to integrate it through Pomodone which would give an easy route to getting a bunch of integrations for users of Pomodone for time tracking.

Let me know your thoughts.

Thanks

**Comment by ryneeverett** [comment]
It's a safe bet that an Asana integration would be accepted, though there are no plans that I know of to build one at present. We generally accept integration with any service that fits the task/bug tracking pattern.

**Comment by ryneeverett** [comment]
Going to close this (cleaning up the queue). However, do see https://github.com/ralphbean/bugwarrior/pull/410 for anyone who wants to contribute this as a patch.
