### ISSUE TITLE
Odoo integration

### ISSUE THREAD

**Issue by rubdos** [ralphbean/bugwarrior#738]
Hello!

I've only just started using TaskWarrior and BugWarrior today, so I am uncertain whether this is wanted, feasible and whether I'll use it in the long term myself.  As such, feel free to close this when you feel like I dropped it in a few months :'-)

I am using Odoo to write invoices and track projects with customers.  Odoo has a [project](https://www.odoo.com/page/project-management) and [CRM](https://www.odoo.com/page/crm) module. The former has a Project -> Task style structure, the latter is a Kanban-style board.

As said: I am wondering whether integration would be useful/wanted/used/interesting/...  If I indeed start to use TaskWarrior on daily basis, I see myself contributing this fairly soon.

**Comment by ryneeverett** [comment]
Go for it!

We'd probably want tasks pulled in by default. This would be a minimum merge-able implementation. If you wanted you could also implement an option to include board items and this would be controlled by a configuration option.

**Comment by rubdos** [comment]
Good! Give me some days to get used to my new workflow. Feel free to assign me this issue (it should get pulled in automatically in an hour then); when I start to get used to my new workflow, I'll jump right on it.

**Comment by rubdos** [comment]
So, in the end it seems like I'm using TaskWarrior for whatever I'd do in Odoo's CRM any way. This is showing up as my next task now, but I don't think it's worth it for me, atm. I'll unassign myself, if that's alright!

**Comment by ryneeverett** [comment]
That's perfectly fine. I'm going to close this for now. However, do see #410 for anyone who wants to contribute this as a patch.
