### ISSUE TITLE
JIRA: Basic authentication with passwords is deprecated.

### ISSUE THREAD

**Issue by StephanMeijer** [ralphbean/bugwarrior#750]
```bash
$ curl -u "EMAIL:PASSWORD" -X GET -H "Content-Type: application/json" "https://BASEURI/rest/api/latest/serverInfo"
Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html
```

```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [jira]
WARNING:root:Got recoverable error from GET https://digibri.atlassian.net/rest/api/latest/serverInfo, will retry [1/3] in 14.381403073578113s. Err: 401 Unauthorized
```

**Comment by StephanMeijer** [comment]
I will be fixing this bug myself.

**Comment by ryneeverett** [comment]
Beyond documentation, perhaps we should make a call to `self.jira.server_info()` in `JiraService.__init__` so we can pass the warnings through to bugwarrior users?

**Comment by StephanMeijer** [comment]
> Beyond documentation, perhaps we should make a call to `self.jira.server_info()` in `JiraService.__init__` so we can pass the warnings through to bugwarrior users?

Yeah maybe. Shall we seperate it into a new ticket?

**Comment by ryneeverett** [comment]
We can open a new ticket or leave this one open.

**Comment by twaugh** [comment]
See also #853.

**Comment by Miuler** [comment]
> I will be fixing this bug myself.

@StephanMeijer 
Please create pull request in upstream repo

**Comment by ryneeverett** [comment]
@Miuler Is there anything we ought to do here besides improving the error message?

**Comment by Miuler** [comment]
> @Miuler Is there anything we ought to do here besides improving the error message?

@ryneeverett 
It's just documentation, use the created token instead of the real password
