### ISSUE TITLE
Support not syncing description

### ISSUE THREAD

**Issue by djmitche** [ralphbean/bugwarrior#766]
I'm copied on repos that see a lot of large issues with lots of comments.  This generates a huge quantity of updates, each of which includes its own copy of all of that traffic, ballooning the task data that must be sync'd.  And, I don't need any of that -- I just need a link to the issue.

Separately, [certain characters in the subject of an issue will tickle](https://github.com/ralphbean/bugwarrior/issues/527) https://github.com/GothenburgBitFactory/taskwarrior/issues/2140 which means that *every* bugwarrior run "modifies" the task.

It'd be great to have a way to disable the sync of comments to annotations.

**Comment by ryneeverett** [comment]
Is this different than setting `annotation_comments=False`?

**Comment by djmitche** [comment]
Indeed, I slightly misunderstood the problem.  I'm seeing huge blobs of text from issues and PRs with large initial comments like https://github.com/taskcluster/azure-entities/pull/169.  In fact, when these comments are changed (such as to check a checkbox), that generates a modification.

So perhaps a `github.ignore_body=True` option?

**Comment by ryneeverett** [comment]
<s>I think `github.annotation_description=False` (default: True) would be more consistent with our existing options.</s> *(edit: I forgot that the description is not implemented as an annotation but is a top level field)* Also, I suspect that it would be just as easy to make this option available to all services.

**Comment by ryneeverett** [comment]
Perhaps a better plan yet would be `github.description_length=0` (default: 500,000?). Implementing this option would also resolve #304.

**Comment by djmitche** [comment]
I'm tempted to work on this but history suggests you'll have an even better idea in T-20 days ;)

(seriously, I'm hoping to get to it this week.. I have the week off and I'm sprinting on https://github.com/djmitche/taskchampion)

**Comment by ryneeverett** [comment]
> (seriously, I'm hoping to get to it this week.. I have the week off and I'm sprinting on https://github.com/djmitche/taskchampion)

Very interesting work at taskchampion. Do you think it would be practical to develop a python api library (say "taskc") as a drop-in replacement for taskw so we could use bugwarrior with it?

**Comment by djmitche** [comment]
It won't be "drop in", because the data model is different, but one of the
goals is that TC be something that is easier to integrate with (so an
actual library instead of executing a process).

Hopefully it would be relatively straightforward to make bug warrior able
to integrate with both tools, without forking "bugchampion" :)
