### ISSUE TITLE
Feature request: create RabbitMQ-support for queuing tasks.

### ISSUE THREAD

**Issue by StephanMeijer** [ralphbean/bugwarrior#771]
Also see #770.

**Comment by ryneeverett** [comment]
Can you give an example use case?

**Comment by StephanMeijer** [comment]
For example IOT where I want to queue tasks

**Comment by ryneeverett** [comment]
So you're suggesting we queue tasks from the taskwarrior database to be consumed by some component of an iot infrastructure?

**Comment by StephanMeijer** [comment]
Nope, For example:

When my camera triggers, it could send the pictures to my AI. If my AI thinks there is a cat present, it could queue a task: _Remove cat from kitchen_

I'd like a system where Bugwarrior can empty the queue and import new tasks.

**Comment by ryneeverett** [comment]
Wouldn't it be simpler to use your proposed HTTP API and have the server serving that endpoint consume and aggregate the queue rather than teaching bugwarrior to consume the queue?

**Comment by ryneeverett** [comment]
I'm going to close this for now in the absence of a compelling argument that this functionality should be included in the scope of this project.
