### ISSUE TITLE
Handle `project_name` as a first class property: just like `default_priority`

### ISSUE THREAD

**Issue by StephanMeijer** [ralphbean/bugwarrior#776]
This'll enable us to use `default_project` globally, just like we can use `default_priority` globally.

**Comment by ryneeverett** [comment]
To be clear, by "first class property" and "globally" we're referring to the fact that you can use it across all services, correct?

Why can't we stick with `project_name` for consistency and backwards compatibility?

**Comment by StephanMeijer** [comment]
We sure can do that.

**Comment by ryneeverett** [comment]
I'd forgotten that [field templates](https://bugwarrior.readthedocs.io/en/latest/common_configuration.html#field-templates) can be used to achieve the same effect. (`SERVICE.project_template = Office`) Would it make more sense to deprecate the existing `project_name` options?

**Comment by StephanMeijer** [comment]
Yep.
