### ISSUE TITLE
Why is `default_priority` equal to `"M"` by default?

### ISSUE THREAD

**Issue by StephanMeijer** [ralphbean/bugwarrior#780]
When no `default_priority` given, I would expect no default priority (`None`) to be given to the issues, and not `"M"`.

**Comment by StephanMeijer** [comment]
Also see #778

**Comment by ryneeverett** [comment]
This was mentioned in #426. I agree that this would be a better default but I'm not sure there's a graceful way to make the change at this point. This would be a drastic disruption of the priority economy in existing databases in which users may have already adjusted their coefficients in line with bugwarrior's default [per the docs](https://taskwarrior.org/docs/priority.html).

**Comment by StephanMeijer** [comment]
Closed: duplicate of #426
