### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by djmitche** [ralphbean/bugwarrior#784]
I just reinstalled bugwarrior, and #668 came back.  I think, right now, the bugzilla service is 100% broken in the latest release, but works from the `develop` branch.

Time for 1.7.1?

**Comment by ryneeverett** [comment]
Definitely time for a release, though I think switching to datever might make more sense for this project because the stability we're chasing is a moving target (third party API's we can't control).

**Comment by djmitche** [comment]
"datever" meaning https://calver.org/?  Yeah, that makes sense to me.

**Comment by ryneeverett** [comment]
> "datever" meaning https://calver.org/?

Yes, I couldn't remember what it was called.

I sent ralph an email as I'm not sure he sees github notifications any more.

**Comment by evilham** [comment]
<3 I was coming to check precisely this, just realised that without some patches that I had already landed in develop some months ago, things like `phabricator` are broken :-D.

**Comment by ryneeverett** [comment]
I see @coddingtonbear has tagged a release on taskw. I presume he's in the same situation of being unable to push to pypi so perhaps we can follow his lead on how to handle this.

Cross-reference: https://github.com/ralphbean/taskw/issues/137

**Comment by coddingtonbear** [comment]
Oh, hey everybody!  I sent an e-mail to @ralphbean yesterday to see options we might have (either continuing to ping him for releases, or granting pypi maintainership to folks).  I'll let you all know when I hear back.

**Comment by coddingtonbear** [comment]
:wave: I officially have the credentials necessary to upload packages to PyPI for Bugwarrior. I'm a little out of the loop, though, about what's going on in Bugwarrior, so we should probably talk on #taskwarrior or somewhere else to discuss things.

**Comment by ryneeverett** [comment]
1.8 is released! Thanks @coddingtonbear!

@coddingtonbear and I had a private chat about calver and he's convinced me to stick to semver. The main points:

- Bugwarrior is likely being used as a library by some folks and semver communicates the API compatibility. In my opinion internal API compatibility is not a reasonable expectation for applications unless the API is documented or it is at least communicated by the maintainers that usage as a library is supported. @coddingtonbear does not agree with this. Perhaps we can agree that documenting the API or at least the fact that library usage is supported wouldn't do any harm. (#791)
- The point that really got me was that we'd have no way to communicate backwards incompatible changes in our command line interface or configuration options. Users (and distributions) would have no way of distinguishing between incompatible changes and patch releases.

**Comment by djmitche** [comment]
We had a similar problem with Buildbot back in the day -- we hadn't been explicit about what was and wasn't an API, and we had some autogenerated API docs that basically made everything look like an API.

You'd be within your rights to say somewhere that this is *only* a command line tool and exposes no Python API.  But, a semver approach with some clear definition for what is and isn't in scope as an API is fine too.
