### ISSUE TITLE
github: "depends on" breaks things

### ISSUE THREAD

**Issue by srl295** [ralphbean/bugwarrior#803]
This fails in taskw:

```shell
$ task add project:srl description:"TEST" githubbody:"depends on #999999999999999\n"
The value is not an expression.
```

Somehow, task doesn't tell me _what_ isn't an expression. I guess it's parsing the 'depends' somehow. 

I don't know if this is a taskw bug, or something bugwarrior should workaround.

**Comment by srl295** [comment]
looks like it may be fixed in https://github.com/GothenburgBitFactory/taskwarrior/issues/2257

**Comment by ryneeverett** [comment]
I suspect this is the same issue as #733, though the workaround of https://github.com/ralphbean/taskw/pull/135 wouldn't work here. I'd be curious to see if https://github.com/GothenburgBitFactory/taskwarrior/pull/2405 fixes both these issues.

**Comment by srl295** [comment]
> I suspect this is the same issue as #733, though the workaround of https://github.com/ralphbean/taskw/pull/135 wouldn't work here. I'd be curious to see if https://github.com/GothenburgBitFactory/taskwarrior/pull/2405 fixes both these issues.

The code path in question already uses `description:"blah.."` as above, so if I'm understanding correctly it wouldn't work as a workaround.

I am working around it by rewriting my issue descriptions. Changing the human language to match the tool 😀

**Comment by ryneeverett** [comment]
I suspect this is fixed in recent taskwarriors, per https://github.com/ralphbean/bugwarrior/issues/733#issuecomment-1111670214.
