### ISSUE TITLE
Travis Builds Failed Due to new Rust Dependency In Cryptography

### ISSUE THREAD

**Issue by cam-barts** [ralphbean/bugwarrior#809]
[Example Failed Travis Link](https://travis-ci.org/github/ralphbean/bugwarrior/jobs/764707610)

It looks like the cryptography package now requires Rust. This isn't available in the ppc64le travis build architecture. Here is a [relevant PR](https://github.com/pyca/cryptography/issues/5771). 

There seem to be a couple of routes here. The easy way looks like to explicitly install Rust and update pip, but I suppose you can also set the variable in the Build config.

**Comment by ryneeverett** [comment]
Thanks for the report. Resolved via #774 by installing rust.
