### ISSUE TITLE
--version flag

### ISSUE THREAD

**Issue by ryneeverett** [ralphbean/bugwarrior#811]
It would be nice if we could (ask bug reporters to) call `bugwarrior --version` for debugging purposes. Blocked by #342.

**Comment by Fongshway** [comment]
A potential nice extension of this would be to have a command similar to `task diagnostic` that prints out a whole bunch of system information in addition to the version number for debugging purposes.

**Comment by ryneeverett** [comment]
> A potential nice extension of this would be to have a command similar to `task diagnostic` that prints out a whole bunch of system information in addition to the version number for debugging purposes.

Yeah, I was thinking about adding an issue template requesting a few items of diagnostic information, but it would be better to just have one command that gives us everything we need. So much the better if we can copy the upstream cli api to minimize the learning curve.
