### ISSUE TITLE
Gitlab: Default priority only respected for issues?

### ISSUE THREAD

**Issue by fmauch** [ralphbean/bugwarrior#814]
Fiddling around with priority setup, noticed, that the configured default priority for gitlab is only used, if the item is an "issue", see [here](https://github.com/ralphbean/bugwarrior/blob/develop/bugwarrior/services/gitlab.py#L140-L141).

Is there any reasoning behind this? Seems like this got hardcoded at some point because it fitted someone's workflow, but maybe I am missing something here.

If there's no deeper intention behind this, I'd be happe to create a PR changing this, but first I wanted to make sure...

As Gitlab AFIAK doesn't use any priority flag, I think the valid approaches would be to
 1. use one default priority for everything
 1. let the user configure different priorities for different types

I would be fine with **1.**, but I am someone not working with priorities at all, anyway....

**Comment by ryneeverett** [comment]
I don't recall if there was a rationale but it's probably more of a historical artifact. I think both solutions would probably be acceptable.

**Comment by ryneeverett** [comment]
Resolved via #816.
