### ISSUE TITLE
Add timeouts to CI

### ISSUE THREAD

**Issue by marcfargas** [ralphbean/bugwarrior#834]
Hi,

A [PR run just took 72hrs](https://github.com/ralphbean/bugwarrior/actions/runs/1117935250) on Actions (until it was killed by GitHub). That will most likely have eaten through all the free minutes allowance from GitHub.

A quick solution to prevent that is to include lower timeouts on the [jobs](https://github.com/ralphbean/bugwarrior/blob/develop/.github/workflows/bugwarrior.yml) see [docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes).

**Comment by ryneeverett** [comment]
Lowering the default timeout from 6 hours is probably a good idea, thanks.

I'm not completely comfortable interpreting the Actions UI but my impression is that it timed out failing to actually start any jobs, which shouldn't have counted towards the budget. Either way no job should have been able to last beyond the default 360 minutes.
