### ISSUE TITLE
Allow truncating / eliminating trello descriptions, as with github and jira

### ISSUE THREAD

**Issue by djmitche** [ralphbean/bugwarrior#835]
Yep, I have to use Trello *and* Jira.  I am truly blessed.

At least with this change, I can avoid being blessed with constantly-changing huge Taskwarrior tasks :)

**Comment by djmitche** [comment]
@ryneeverett should we stick with the body-size option, or is it time to add a different shared config knob for this?

**Comment by ryneeverett** [comment]
Are you asking about a global `body_length` option? I think that would indeed be reasonable, especially considering that many users probably use bugwarrior similarly to you and just need the link.

**Comment by djmitche** [comment]
I was thinking of something like `sync_descriptions` defaulting to true, or `titles_only` defaulting to false, or something like that.

**Comment by djmitche** [comment]
Huh, I just discovered that I can do this with `static_fields`!

I'll make a docs update to help with this.
