### ISSUE TITLE
Gitlab: support and/or document gitlab.only_if_assigned = myusername

### ISSUE THREAD

**Issue by StephanMeijer** [ralphbean/bugwarrior#856]
As a user of this integration I would like to be able to filter on tickets where only I am assigned. The rest is irrelevant for me.

![image](https://user-images.githubusercontent.com/3169264/145371655-12177d8c-5811-4a92-ad76-6d75f1e2f29b.png)

**Comment by ryneeverett** [comment]
This is documented as a [common service configuration option](https://bugwarrior-docs.readthedocs.io/en/latest/common_configuration.html#common-service-configuration-options) and is (presumably) supported.
