### ISSUE TITLE
Document how to get trello.token

### ISSUE THREAD

**Issue by StephanMeijer** [ralphbean/bugwarrior#857]
Currently this is documented as:

> Trello token, see below for how to get it.

For me it is totally unclear how to get this token.

**Comment by leandrochiarini** [comment]
Having the same problem here

**Comment by ryneeverett** [comment]
Hmm. I'll admit this is definitely an error in our documentation but I'm surprised it's not easy to figure out. Searching the web for "trello token" I see varying instructions, for example:

- https://altosio.com/trello-migration-guide/
- https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/

Do none of these work?

**Comment by leandrochiarini** [comment]
Sorry, they did. The reason I thought I had something wrong with my token was actually due to some old python packages.

**Comment by ryneeverett** [comment]
Great! Could you tell us which guide you followed or what method you used to get the token (for posterity)?

**Comment by leandrochiarini** [comment]
Of course, 

1. Go to [https://trello.com/app-key/](https://trello.com/app-key/)
2. Under Personal key, click on the link in "you can manually generate a Token" (in the word Token)
3. Allow for the new server token.

Should I submit a PR for the documentation?

**Comment by ryneeverett** [comment]
@leandrochiarini Yes, please do!
