### ISSUE TITLE
Feature Request: Jira Parent & Custom fields

### ISSUE THREAD

**Issue by d-miketa** [ralphbean/bugwarrior#860]
Jira's integration can already pull information about subtasks; adding another field for the parent ID should be almost trivial, yet very useful.

Jira also seems to allow users to specify custom fields labelled as e.g. `customfield_12345`. (As far as I can tell it's always `customfield` followed by a 5-digit number.) These fields can be strings, numerics or any other type. It'd be useful to be able to pull them into the task, too, though that seems like a more involved effort (customisable UDA?).

**Comment by ryneeverett** [comment]
Resolved via #861 and #862.
