### ISSUE TITLE
Does bugwarrior do two-way sync with any remote?

### ISSUE THREAD

**Issue by YAMLcase** [ralphbean/bugwarrior#863]
Sorry to ask this in an issue, but I couldn't find the answer readily.  Does bugwarrior also update the remote ticket/issue when annotating or changing any metadata?  i.e., I close an issue in taskwarrior and bugwarrior then closes the linked issue in github.  Thanks

**Comment by ryneeverett** [comment]
No.

This has come up a few times but our lack of a universal terminology to describe it makes search difficult. Here's an example: #135.

Perhaps we should add this to the FAQ.

**Comment by YAMLcase** [comment]
Ok thanks for the clarification.

**Comment by ryneeverett** [comment]
I would note that while the maintenance burden of such a feature seven years ago would have been unbearable, the project has matured a lot since then and such an optional feature could probably be added and maintained fairly cheaply now.

**Comment by ryneeverett** [comment]
Related: #658
