### ISSUE TITLE
Support for Fossil SCM

### ISSUE THREAD

**Issue by umonkey** [ralphbean/bugwarrior#87]
Here's a Fossil SCM scraper.

http://code.umonkey.net/bugwarrior/raw-file/default/bugwarrior/services/fossil.py

I'm using it with version 0.5.3.  I can't test it with the latest code currently because of some local dependency issues.

**Comment by mathstuf** [comment]
Hmm. seems the file has disappeared but @FvD has it copied down. I see some issues with it (no `@oracle` support, not using `super`, and `urllib2` rather than `requests`), but other than those issues, I don't see why it wouldn't be accepted.

**Comment by ralphbean** [comment]
Going to close this (cleaning up the queue).  See also #410 for anyone who wants to contribute this as a patch.
