### ISSUE TITLE
growlnotify is discontinued

### ISSUE THREAD

**Issue by srl295** [ralphbean/bugwarrior#875]
re: #59 

https://growl.github.io/growl/ says

> Growl is a retired project, we couldn’t think of another thing to change which would be substantial enough to bring out a new updated release. Growl is stable and should work for as long as intel based programs work. Anyone who wants to run Growl is free to do so in an unsupported fashion.

Ideally switch to use the macos native notify…

**Comment by ryneeverett** [comment]
Reopening until we add a deprecation warning to growlify.
