### ISSUE TITLE
[Redmine] Add project_id to arguments to retrieve issues

### ISSUE THREAD

**Issue by CaptainQuirk** [ralphbean/bugwarrior#883]
Hi there,

I would like to know if it was possible to add a `project_id` configuration that would be used as a filter when getting the issues from Redmine ?

Thanks in advance !

**Comment by ryneeverett** [comment]
Looks like this service is missing a way to filter issues. If possible, I'd prefer a more general "query" configuration field which would allow filtering against arbitrary parameters in the redmine api.

**Comment by CaptainQuirk** [comment]
I could take care of that ! What form do you have in mind ? 
Would simply a `query: string` property of the configuration class that would be appended to the `assigned_to_id` ?
Something like that : 
```
redmine.query = project_id=42&status_id=!666
```
?

**Comment by ryneeverett** [comment]
I would take a look the github and gitlab services for examples of how we handle `query` strings.

Your configuration field and configuration example look correct, but I don't think we would append them to the `assigned_to_id`. To allow for maximum flexibility without configuration sprawl, we've been having `query` strings completely override the "conventional" bugwarrior query, so if you still wanted to limit by assignee you'd have to add that to the query string.

If possible, it might be nice to implement `assigned_to_id=me` as the default `query` string if it's possible to avoid alternate code paths -- but it's not always possible.

cc @fmauch

**Comment by CaptainQuirk** [comment]
I just opened #886 !

**Comment by ryneeverett** [comment]
Resolved in #886.
