### ISSUE TITLE
bugwarrior-bugwarrior pull is deprecated

### ISSUE THREAD

**Issue by srl295** [ralphbean/bugwarrior#901]
```
$ bugwarrior pull
Deprecation Warning: `bugwarrior-bugwarrior pull` is deprecated and will be removed in a future version of bugwarrior. Please use`bugwarrior bugwarrior pull` instead.
```

I didn't try `bugwarrior bugwarrior pull` yet.  What I did do is:

1. update to latest `develop` ea9c6d72d01c318b105ac9b1a5b21eec78d3178d
2. `python3 setup.py install`
3. symlinked `/usr/local/bin/bugwarrior -> /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/bugwarrior`

maybe user error somewhere…

**Comment by ryneeverett** [comment]
Resolved by #900.
